### ISSUE TITLE
List Index out of range when calling cam 

### ISSUE THREAD

**Issue by cdsarto** [jacobgil/pytorch-grad-cam#101]
Hello @jacobgil,

I have some issues implementing the grad-cam:

This is my code:
```
target_layer = model.layer4[-1]
img_path = ..


#Preprocess your data and feed it to the model
rgb_img = cv2.imread(img_path, 1)[:, :, ::-1]
rgb_img = np.float32(rgb_img) / 255
input_tensor = preprocess_image(rgb_img, mean=[0.485, 0.456, 0.406], 
                                            std=[0.229, 0.224, 0.225])

cam = GradCAM(model=model, target_layer=target_layer, use_cuda=False)

target_category = 1
grayscale_cam = cam(input_tensor=input_tensor, target_category=target_category)
```

As a model I used a pretrained ResNet50.

And this is the error message:

> IndexError                                Traceback (most recent call last)
> <ipython-input-64-4eb7a9d6b5ac> in <module>
>      22 target_category = 1
>      23 print(input_tensor.shape)
> ---> 24 grayscale_cam = cam(input_tensor=input_tensor, target_category=target_category)
>      25 
>      26 # grayscale_cam = grayscale_cam[0, :]
> 
> /mnt/batch/tasks/shared/LS_root/mounts/clusters/standard-f4s-v2/code/Users/module_/pytorch_grad_cam/base_cam.py in __call__(self, input_tensor, target_category, aug_smooth, eigen_smooth)
>     127 
>     128         return self.forward(input_tensor,
> --> 129             target_category, eigen_smooth)
> 
> /mnt/batch/tasks/shared/LS_root/mounts/clusters/standard-f4s-v2/code/Users/module_/pytorch_grad_cam/base_cam.py in forward(self, input_tensor, target_category, eigen_smooth)
>      72 
>      73         activations = self.activations_and_grads.activations[-1].cpu().data.numpy()
> ---> 74         grads = self.activations_and_grads.gradients[-1].cpu().data.numpy()
>      75 
>      76         cam = self.get_cam_image(input_tensor, target_category, 
> 
> IndexError: list index out of range
> 

It would be great if you could help me :)

Cheers``

**Comment by jacobgil** [comment]
Looks like there are no gradients.
Can you please give more context - are you running the model on several images? Is the Resnet50 model the same as in torchvision?
