### ISSUE TITLE
Is my 3D Grad CAM implementation Correct?

### ISSUE THREAD

**Issue by chuanyang-Zheng** [jacobgil/pytorch-grad-cam#102]
1. Change 

https://github.com/jacobgil/pytorch-grad-cam/blob/c6e820df00656481b00d0ee97e438345422cd5e7/pytorch_grad_cam/grad_cam.py#L16 

To

return np.mean(grads, axis=(2, 3,4))

2. Change 

https://github.com/jacobgil/pytorch-grad-cam/blob/c6e820df00656481b00d0ee97e438345422cd5e7/pytorch_grad_cam/base_cam.py#L47

To

weighted_activations = weights[:, :, None, None,None] * activations

3. A question is: How do I change the following

https://github.com/jacobgil/pytorch-grad-cam/blob/c6e820df00656481b00d0ee97e438345422cd5e7/pytorch_grad_cam/base_cam.py#L83

img = cv2.resize(img, input_tensor.shape[-2:][::-1])

      1) Why we need [::-1]
      2) How to modify the line so that we can use it for 3D Grad-CAM?

Best regards

**Comment by jacobgil** [comment]
Hi,
input_tensor.shape[-2 : ] contains the tensor dimensions, which are height x width.
Opencv expects (width, height) -> hence the [::-1].
For your use case, you will have to resize similarly the 3D image.
What are the dimensions of the image?
One option would be to loop and resize every slice, like this: 
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/fullgrad_cam.py#L45

Closing this issue,
Please re open it and let me know if you have any other questions.

**Comment by vctorwei** [comment]
Hi, 
Can you be more specific about how to change
`img = cv2.resize(img, input_tensor.shape[-2:][::-1]) `?

I only changed  `return np.mean(grads, axis=(2, 3))`  and  
`weighted_activations = weights[:, :, None, None] * activations `

Now whenever I change the target layer, my generated CAM change as well.
for example, my input image is 4,56,56,56, but my CAM map will be like 4,56,56,26, for layer 1 or 4,56,56,3 for layer 3.

Do I resize 26 or 3 to 56 for visualization?

My CNN network is in [issue](https://github.com/jacobgil/pytorch-grad-cam/issues/142) 

Thank you
