### ISSUE TITLE
show_cam_on_image param use_rgb

### ISSUE THREAD

**Issue by AtharzWang** [jacobgil/pytorch-grad-cam#103]
In cam.py, I already uses rgb format, but the default param use_rgb is false, so which is the correct?

**Comment by jacobgil** [comment]
Can you please clarify what you mean?
use_rgb=True is passed as true in cam.py, but the default is false. 
Do you mean the default should be true?

**Comment by AtharzWang** [comment]
Yes. I think the default should be true.
