### ISSUE TITLE
Error while running cam.py

### ISSUE THREAD

**Issue by Aniruddha7** [jacobgil/pytorch-grad-cam#104]
Hi, I am trying to run cam.py using pretrained DenseNet model and I am getting this warning while running the cam.py script. Can anyone please help to resolve this?
![image](https://user-images.githubusercontent.com/19803877/122804201-398fc800-d2e5-11eb-9352-10ca8e527f48.png)

**Comment by jacobgil** [comment]
I think this error is because we're using register_backward instead of register_full_backward_hook.
But this should be only a warning about changing to that api in the future, and the result should still be correct.
