### ISSUE TITLE
Support for LayerCAM

### ISSUE THREAD

**Issue by PengtaoJiang** [jacobgil/pytorch-grad-cam#106]
Our paper "LayerCAM: Exploring Hierarchical Class Activation Maps for Localization" is accepted by TIP recently, which can visualize the class activation maps from any cnn layer of an off-the-shelf network. Could you add our method to your popular repository for more people to try this method? Our method is a simple modification of Grad-CAM. It should easy to implement. Here is the [paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9462463) and [code](https://github.com/PengtaoJiang/LayerCAM). Hope for your reply.

**Comment by jacobgil** [comment]
Hello, I will add this. 
I'm out right now so it might take me about a week or so, but I will add it.

**Comment by PengtaoJiang** [comment]
Thanks a lot.

**Comment by jacobgil** [comment]
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/layer_cam.py#L18
It's implemented now, and also added to the Readme.

**Comment by jacobgil** [comment]
In the paper you used a CRF for combining channels from multiple layers, for weakly supervised localization.
I think this would be a great addition to this repository.
Do you have some pointer on where to get started with this, maybe a recommended python CRF library for combining the channels?

**Comment by PengtaoJiang** [comment]
@jacobgil Hi, I just use a simple element-wise maximum fusion to combine cam from multiple layers.   Additionally, could you please note that for those layers that are followed by a layer (max pooling in vgg or conv with stride > 1 in resnet), the cam visualizations usually have grid effect. This issue comes from the gradient backward. I usually choose the nearby layers for visualization.  For example, pool4 instead of conv3_3 in vgg16, or model.layer3[-2] instead of model.layer3[-1].

**Comment by jacobgil** [comment]
Thanks!

**Comment by RoyVoetman** [comment]
> the cam visualizations usually have grid effect. This issue comes from the gradient backward. I usually choose the nearby layers for visualization. 

Thanks! I came across this problem as well!
