### ISSUE TITLE
 invalid value encountered in true_divide, what's wrong with my input and how to solve this problem?

### ISSUE THREAD

**Issue by starrywintersky** [jacobgil/pytorch-grad-cam#107]
/usr/local/lib/python3.6/site-packages/pytorch_grad_cam/base_cam.py:85: RuntimeWarning: invalid value encountered in true_divide
  img = img / np.max(img)

**Comment by vivektalwar13071999** [comment]
It's divisible by zero error, the arrays might be returning empty, refer this  - https://stackoverflow.com/questions/27842884/numpy-invalid-value-encountered-in-true-divide

**Comment by jacobgil** [comment]
Yes, probably the entire cam image is negative and then after the relu it's 0.
The reason to why this happens depends on your model and input image.
Perhaphs try with another image or target_category and see if this always happens.
