### ISSUE TITLE
Gradcam ouput different 

### ISSUE THREAD

**Issue by bartproo** [jacobgil/pytorch-grad-cam#113]
My original image size is 1920×1080. I resized it with opencv to 224×224 to save disk space. However, the cam results of feeding these data differ significantly as compared to feeding the model with original image with the size 1920×1080? Any reason causing this? I checked that both torchvision and opencv are using the same interpolation method. So should not be cause by the interpolation.  What could it be then?

**Comment by jacobgil** [comment]
The features computed by the CNN are different in both images, corresponding to different scales.
Assuming you are using a Resnet50  classifier for example, in the first case  the output from the CNN will be 2048x60x60, followed by global average pooling.
In the second case it will be 2048x7x7.
The features computed are different.

**Comment by bartproo** [comment]
Thanks for the ans
