### ISSUE TITLE
Possibility to declare our own augmentations for aug_smooth = True

### ISSUE THREAD

**Issue by mhashas** [jacobgil/pytorch-grad-cam#118]
Hi,

Thanks for the library. Would it be possible for us to declare our own augmentations. Right now I am superclassing your class

**Comment by jacobgil** [comment]
Hi,
Yes indeed. 
I think one option would be to pass a transforms to the constructor, that defaults to `transforms = tta.Compose(
            [
                tta.HorizontalFlip(),
                tta.Multiply(factors=[0.9, 1, 1.1]),
            ]
        )`
if transforms is not passed.

A PR will be welcome!
Otherwise I can in a few days.

**Comment by jacobgil** [comment]
Out of curiosity, since this is a relative new feature - are you getting better results with test time augmentations? What kind of augmentations are you using?

**Comment by mhashas** [comment]
Hi, thanks for the quick response. We do get better results with test time augmentations. Some extra augmentations include gaussian noise.

**Comment by jacobgil** [comment]
Are the augmentations you're using support the `augment_image` and `deaugment_mask` methods? e.g are they from the ttach library?
I'm about to push a fix where you can just specify the `aug_smooth_transform`, but want to make sure that's enough.

**Comment by mhashas** [comment]
Hi,

Unlike HorizontalFlip and Multiply, these ones do not modify the "structure of the image", just the pixel values, so deaugment_mask should just return the mask. In my case, I had a check if deaugment_mask is available and if not I just let me mask as is . 

There's probably a cleaner way of doing this (?) or at least showing a warning to the user "hey this transform that you gave me doesn't have deaugment mask so im just going to use the mask, make sure thats fine". This can be a bit tricky tho, as if you're not carefull (or knowledgeable) it can lead to unexpected results

**Comment by jacobgil** [comment]
Implementing this in a generic, easy to use way might be a bit tricky.
There are two ways that I can think of:
1. The user can pass a transforms object, but it has to be built with `ttach.Compose`. If you have a custom transform, you have to implement by deriving from a ttach transform.
2. Maybe pass a list with tuples of (augment_transform, deaugment_transform).
Each of them should be callable.

I'm thinking of doing 2.

Which one do you think is better / maybe another idea of how to do it in a clean way?

**Comment by mhashas** [comment]
I think the second is slightly more flexibile, as it allows users to pass custom transforms and use indentity function for deaugment transform

**Comment by jacobgil** [comment]
Hi,
I have a branch for this, but keeping this on hold for now.
It will make it more flexible, but will make the API a bit more complex to use and I'm not sure it's a good trade off.
