### ISSUE TITLE
Predicted Target Category does not matches with Imagenet Category

### ISSUE THREAD

**Issue by nbansal90** [jacobgil/pytorch-grad-cam#119]
Hi @jacobgil ,

Thank you for sharing the code!
I was trying out on VOC dataset, every things works well, apart from one thing, which is; the predicted `target category` is not right when compared with official  Imagenet id. For example for following image:
![grad_cam](https://user-images.githubusercontent.com/12581965/127586532-ea3bc9a7-b627-4053-a83d-679744f7adbc.jpg)

Shows `target category` as 417, which corresponds to `ballon` rather than plane.(using the link [https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a](url)

Question:

- Is it something which is generally seen,Since it depends upon what the network is seeing?
- If not, is there a different interpretation of the same result

Regards,
Nitin Bansal

**Comment by jacobgil** [comment]
Hello,
In some cases the model could be just wrong. Maybe the baloon score scored higher than plane here.
Are there also VOC images the images is correct about?
Or is it wrong in most cases?

**Comment by nbansal90** [comment]
@jacobgil There are few other cases too, where the predicted category is wrong, but the region of interest (highlight region), is correct in all of them. For Dog and Cat Target Category is correct, but I also stumbled upon an image which consisted of Train, it was able to correctly zero down on the area of interest, but failed to predict the correct cateogry.

**Comment by nbansal90** [comment]
Hey @jacobgil,

I had an extra thought about the grad cam application. I was actually trying out `GradCAM` for `CityScapes` Dataset. So, In Cityscapes Dataset we can multiple instances of an object say `car` or `people` etc. So, we are not concentrating on classifying a single object as one of the class but could have multiple instances of multiple classes.

I find that, If I simply use `GradCAM` for cityscapes images, results do not look that informative per say. For example:
![grad_cam](https://user-images.githubusercontent.com/12581965/127690975-6494f250-3ed5-4cd9-b8f7-c74fe35fe06f.jpg)
![grad_cam_gb](https://user-images.githubusercontent.com/12581965/127690992-940b81be-bc55-473f-a835-68479f2bc45f.jpg)

Now this could be because of two probable reason:

- `Resnet50` is pertained on ImageNet and not on Cityscapes
- `Resnet50`  which is the underlying network used for capturing `gradient` and `activation` is a classification network and not an Object detection network.

Do, you think we can use a pertained version of say `FasterRCNN` or `RetinaNet` instead of `Resnet50` for a dataset such as Cityscapes to get the grad/activation visualization for such a dataset.

Regards,
Nitin Bansal

**Comment by jacobgil** [comment]
- Yes, but using grad-cam for object detection is more difficult and currently not supported in this repo (although I'm thinking of adding it in the future).
- Try using a specific category like "Traffic light" (920 in imagenet). In the image above what was the target category? Since there are many objects, the classifier might have failed. You might want to focus it and try again.
- To get the bounding box, use opencv findContours:
`_, contours = cv2.findContours(binary_heatmap)
for contour in contours:
x,y,w,h = cv.boundingRect(cnt)
#do something with it here..
`

If the classifier correctly classifies or not, is out of control of the visualization method. Many times the salient part might still appear in the incorrectly classified  target_category.
You might want to target specific categories instead of passing target_category=None.

**Comment by nbansal90** [comment]
@jacobgil Thank you for your prompt response. Please find my answers inline:

- Yes, but using grad-cam for object detection is more difficult and currently not supported in this repo (although I'm thinking of adding it in the future).
- **Cool! May be I can start from my end and see if I able to get something good using any of the existing network. Will keep you posted.**
- Try using a specific category like "Traffic light" (920 in imagenet). In the image above what was the target category? Since there are many objects, the classifier might have failed. You might want to focus it and try again.
- **For me it is actually predicting `919` and `920` which is the traffic light. I can remove `None` and give it a try for a more specific class and see how that turns out to be.**
- To get the bounding box, use opencv findContours:
- **That makes sense! Thank you for your suggestion**

Regards,
Nitin

**Comment by jacobgil** [comment]
Curious if for the image with the traffic-light above, you pass `eigen_smooth=True`, what happens?

**Comment by nbansal90** [comment]
@jacobgil I had already passed both the parameter as `True` which is `eigen_smooth` and `aug_smooth`.  BTW, I just stumbled upon a work which seems to be doing what we require for cityscapes dataset. Its a 2020 paper by name [SEG_GRAD_CAM](https://github.com/kiraving/SegGradCAM).

I have still not gone through this. But may be we could find something interesting here.

**Comment by nbansal90** [comment]
@jacobgil I just gave it an another try by setting the target_category as `817` which is class `sport car` in Imagenet set of 1000 classes. I get bit better results But I presume it is still not good.

![grad_cam](https://user-images.githubusercontent.com/12581965/127700762-d433440c-c9c4-4e13-95fc-5ca07b870ef3.jpg)
![grad_cam_gb](https://user-images.githubusercontent.com/12581965/127700773-6218d3a1-e90c-4a6e-868f-1e6ea92081ef.jpg)

Regards,
Nitin

**Comment by jacobgil** [comment]
Yes.
It might also be that the model isn't good enough in finding cars, since it was trained on ImageNet.
Curios if switching to one of the other methods like ScoreCAM or AblationCAM gives the same result?

**Comment by nbansal90** [comment]
I am getting pretty similar or worse results with other methods . GRADCAM++ provides a slightly better result. But I think methods based on Segmentation or Object detection model, would be better suited for dataset such as Cityscapes or KITTI. I will give it a try for SEG_GRAD_CAM work and see how the results pan out.
