### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dikapiliao** [jacobgil/pytorch-grad-cam#120]
```
`[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
/home/ubuntu/anaconda3/envs/T1.8P3.8/lib/python3.8/site-packages/torch/nn/modules/module.py:795: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
`
```

**Comment by dikapiliao** [comment]
I haven't encountered such a bug. Does anyone know how to solve it？

**Comment by yibuxulong** [comment]
I got a similar question when running at the target_layer of ResNet:
```
UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "
```
and the program will be killed after some times warnings.
I found  #70 solve the problem by replacing register_backward_hook of register_full_backward_hook [https://github.com/jacobgil/pytorch-grad-cam/blob/c009adac84ec83565c88c692a13bd3581e7c24eb/pytorch_grad_cam/activations_and_gradients.py#L12](url) [](url)

**Comment by dikapiliao1** [comment]
Thanks!

**Comment by jacobgil** [comment]
Hi,
Should be fixed in the latest version.
Since older pytorch versions don't have `register_full_backward_hook` I added a check to see if that method exists.

**Comment by dikapiliao1** [comment]
Yes, I have solved this problem. Thank you very much for your help
