### ISSUE TITLE
What if model has multiple outputs?

### ISSUE THREAD

**Issue by ASKanse** [jacobgil/pytorch-grad-cam#121]
Hi, I was working on a model which has 2 outputs (tuple of length 2). And for this model, the grad cam library gave the following error.
```Traceback (most recent call last):
  File "cont_bach.py", line 1514, in <module>
    generate_gradcam_vis(full_model, testloader, mean, std)
  File "cont_bach.py", line 1501, in generate_gradcam_vis
    grayscale_cam = cam(input_tensor=input_tensor, target_category=target_category)
  File "/home/abhiraj/.conda/envs/clam/lib/python3.7/site-packages/pytorch_grad_cam/base_cam.py", line 129, in __call__
    target_category, eigen_smooth)
  File "/home/abhiraj/.conda/envs/clam/lib/python3.7/site-packages/pytorch_grad_cam/base_cam.py", line 70, in forward
    loss = self.get_loss(output, target_category)
  File "/home/abhiraj/.conda/envs/clam/lib/python3.7/site-packages/pytorch_grad_cam/base_cam.py", line 37, in get_loss
    loss = loss + output[i, target_category[i]]
TypeError: tuple indices must be integers or slices, not tuple
```

to work around this problem I changed the following line 
https://github.com/jacobgil/pytorch-grad-cam/blob/8842f19525fd9c74120c2ee66c31f0963c6c43b8/pytorch_grad_cam/activations_and_gradients.py#L35
to this
```
if type(self.model(x)) is tuple: #Manual Change herefor multiple outputs of model
            return self.model(x)[1]
        else:
            return self.model(x)
```

This worked for me but **can this feature be added to the code which supports multiple outputs**?

Thanks for the great library!

**Comment by chengengliu** [comment]
Hi all,
I have similar questions, how to deal with models with multiple inputs and outputs. Which part of GradCAM should be modified?

**Comment by jacobgil** [comment]
Hi,
The code currently assumes that the network outputs the classifier score.

I think the easiest way would be to wrap the model with a new model that returns a single output, and pass that model to the package.

Something like this:

``` python
class SingleOutputModel(torch.nn.Module):
def __init__(self, model):
super(self, SingleOutputModel).__init__(self)
self.model = model

def forward(self, x):
return self.model(x)[0]
```
