### ISSUE TITLE
object detection

### ISSUE THREAD

**Issue by Frank1o** [jacobgil/pytorch-grad-cam#126]
Can support mmdetection?
What can i use it?

**Comment by jacobgil** [comment]
Hi,
Although a popular request, object detection is not supported yet here.

**Comment by jacobgil** [comment]
Hi,
I'm happy to share that now there is a detailed notebook about how to use CAMs for object detection:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.ipynb
