### ISSUE TITLE
License

### ISSUE THREAD

**Issue by raghavgoyal14** [jacobgil/pytorch-grad-cam#13]
Hi,

Thanks for the great work.
Would it be possible for you to add an appropriate license to the work?

I noticed that your corresponding keras implementation is licensed under MIT: https://github.com/jacobgil/keras-grad-cam

Thanks,
Raghav

**Comment by semihcanturk** [comment]
Same here. Solid interpretation that I want to play with, so adding a license would be much appreciated. Thanks!
