### ISSUE TITLE
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'

### ISSUE THREAD

**Issue by Joker00007** [jacobgil/pytorch-grad-cam#134]
I used this code to convit model，and ues my own datasets.But get a problem.

The problem is:
 cam = methods[args.method](model=model,
  File "D:\anaconda\anaconda\envs\ViT\lib\site-packages\grad_cam-1.3.2-py3.8.egg\pytorch_grad_cam\grad_cam.py", line 8, in __init__
  File "D:\anaconda\anaconda\envs\ViT\lib\site-packages\grad_cam-1.3.2-py3.8.egg\pytorch_grad_cam\base_cam.py", line 25, in __init__
  File "D:\anaconda\anaconda\envs\ViT\lib\site-packages\grad_cam-1.3.2-py3.8.egg\pytorch_grad_cam\activations_and_gradients.py", line 11, in __init__
TypeError: 'LayerNorm' object is not iterable
Exception ignored in: <function BaseCAM.__del__ at 0x000002595B6CF550>
Traceback (most recent call last):
  File "D:\anaconda\anaconda\envs\ViT\lib\site-packages\grad_cam-1.3.2-py3.8.egg\pytorch_grad_cam\base_cam.py", line 191, in __del__
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'

![图片](https://user-images.githubusercontent.com/40375714/133109513-3169c230-36ec-41fa-97a4-bf3e139a4129.png)

**Comment by jacobgil** [comment]
Hi, thanks for reporting.
It will be great to try to reproduce.
What is is the network you are using?
Can you share the module definition?

**Comment by jacobgil** [comment]
Ok, I probably figured out the error.
Yesterday the API changed a bit,
Now it expects a list, target_layers.
The VIT usage example wasn't updated.
I'm pushing a fix for this now.

**Comment by jacobgil** [comment]
Updated the vit_example.py code.
Now it is
`target_layers = [model.blocks[-1].norm1]`
Instead of just model.blocks[-1].norm1

**Comment by jacobgil** [comment]
Can you please confirm it works?

**Comment by Joker00007** [comment]
> 
> 
> Can you please confirm it works?

Yes，it can be worked.Thank you very much.

**Comment by Khoa-NT** [comment]
Hi, I just installed by pip (grad-cam 1.3.1)
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-cc53cde6c6b9> in <module>
     11 
     12 # Construct the CAM object once, and then re-use it on many images:
---> 13 cam = GradCAM(model=model, target_layers=target_layers, use_cuda=False)
     14 
     15 # You can also use it within a with statement, to make sure it is freed,

TypeError: __init__() got an unexpected keyword argument 'target_layers'
```
 Currently, it only works with `target_layer` and `target_layer = model.layer4[-1]`
Please update the version on pip

**Comment by RMobina** [comment]
I want to use pretrained ResNet and simply apply grad-cam.But get the following error.

`model1 = resnet50(pretrained=True)
#torch.save(model1, 'ResNet.h5')
#model1 = torch.load('ResNet.h5')
target_layers = model1.layer4[-1]


img_path = "./eagle.jpg"
test_image = Image.open(img_path).convert('RGB')
imgplot = plt.imshow(test_image)
plt.show()

toTensor =  transforms.Compose([
                transforms.Resize((100,100)),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
            ])
input_tensor = toTensor(test_image)

test_image = np.array(test_image)
test_image = cv2.resize(test_image,(100,100))
test_image = test_image.astype('float32')
test_image /= 255.0

imgplot = plt.imshow(test_image)
plt.show()

# Construct the CAM object once, and then re-use it on many images:
cam = GradCAM(model=model1, target_layers=target_layers, use_cuda=True)
grayscale_cam = cam(input_tensor=input_tensor.unsqueeze(0), targets=None)
grayscale_cam = grayscale_cam[0, :]
visualization = show_cam_on_image(test_image, grayscale_cam)
imgplot = plt.imshow(visualization)
plt.show()`

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "/home/ECAPA-TDNN/visualization.py", line 51, in <module>
    cam = GradCAM(model=model1, target_layers=target_layers, use_cuda=True)
  File "/home/Voice/venv/lib/python3.8/site-packages/pytorch_grad_cam/grad_cam.py", line 8, in __init__
    super(
  File "/home/Voice/venv/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 27, in __init__
    self.activations_and_grads = ActivationsAndGradients(
  File "/home/Voice-Privacy-Challenge-2022/venv/lib/python3.8/site-packages/pytorch_grad_cam/activations_and_gradients.py", line 11, in __init__
    for target_layer in target_layers:
TypeError: 'Bottleneck' object is not iterable
Exception ignored in: <function BaseCAM.__del__ at 0x7fa2c2d704c0>
Traceback (most recent call last):
  File "/home/Voice-Privacy-Challenge-2022/venv/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 192, in __del__
    self.activations_and_grads.release()
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'
