### ISSUE TITLE
whl file dependencies

### ISSUE THREAD

**Issue by zacharymostowsky** [jacobgil/pytorch-grad-cam#137]
Hi there, thanks for the great library. I see now you are putting out wheel files. Thank you as well for that.

One thing I noticed is the opencv dependency is missing in the `setup.py` `requires` attribute.

I think this can be easily fixed by adding the below to the `setup.py` file. I tested with the latest version of opencv (4.5.3.56) and all seemed to work fine.

```
install_requires = ["opencv-python>=XX.XX.XX"]
```

Error on import -
```
ModuleNotFoundError: No module named 'cv2'
```

I can raise a PR if you'd like.

Thanks,
Zach

**Comment by jacobgil** [comment]
Hi, thanks for reporting.
A PR will be great!

**Comment by jacobgil** [comment]
Merged, thanks a lot.
