### ISSUE TITLE
Problems on Batch Visualization

### ISSUE THREAD

**Issue by zqh0253** [jacobgil/pytorch-grad-cam#144]
Hi, I am following the basic instruction in the README file to do visualization for a batch of input tensor.
However, all instances in one batch seems to have similar CAM results, but dissimilar between different batches.
My code:

> model = resnet34(pretrained=True) 
> lstmodel = torch.nn.Sequential(*(list(model.children())[:-1]))  
> target_layers = lstmodel[5]
> sample_img = next(iter(train_loader))['img']
> input_tensor = sample_img.cuda()
> rgb_img = sample_img.permute(0,2,3,1).numpy()
> cam = GradCAM(model=lstmodel, target_layers=target_layers, use_cuda=True)
> target_category = None
> grayscale_cam = cam(input_tensor=input_tensor, target_category=target_category)

Batch 1:
![image](https://user-images.githubusercontent.com/32608622/136130710-61063be8-c7a6-42d2-b4ae-1bc28d8d2690.png)
Batch 2:
![image](https://user-images.githubusercontent.com/32608622/136130738-38452267-b792-468e-96fe-3da52fedaa8c.png)

I think this is weird. My model is ResNet34 based. I tried different target-layer and all find this phenomona.

**Comment by jacobgil** [comment]
Hi closing, please re-open if you can provide further details.
