### ISSUE TITLE
Regarding usage issues

### ISSUE THREAD

**Issue by Zengyf-CVer** [jacobgil/pytorch-grad-cam#146]
@jacobgil 
Hello, this is my first contact with your project, and I have a few questions for you:
- Can this project be directly applied to target detection?
- If it can be used for target detection, how should I use it?
- If not, how should I modify it to apply it to target detection?

**Comment by jacobgil** [comment]
Hi,
Currently object detection isn't supported.
This is something I'm looking at and hope to support in the near future.
