### ISSUE TITLE
Getting error when using Densenet: 'Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace'

### ISSUE THREAD

**Issue by kopop8** [jacobgil/pytorch-grad-cam#147]
Hello first I want to say amazing work, your code worked great on my resnet model!
Now i'm trying to get the Cam of a densenet121 model (using layer: model.features[-1]) but I'm getting an error:
```
  File "/densenet_model.py", line 64, in test_cam
    cam_mask = cam(input_tensor=image.unsqueeze(0))
  File "/usr/local/lib/python3.6/dist-packages/pytorch_grad_cam/base_cam.py", line 129, in __call__
    target_category, eigen_smooth)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_grad_cam/base_cam.py", line 59, in forward
    output = self.activations_and_grads(input_tensor)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_grad_cam/activations_and_gradients.py", line 35, in __call__
    return self.model(x)
  File "/export/home/optest/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/export/home/optest/.local/lib/python3.6/site-packages/torchvision/models/densenet.py", line 217, in forward
    out = F.relu(features, inplace=True)
  File "/export/home/optest/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1296, in relu
    result = torch.relu_(input)
RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.

```
RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.

RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.

My code to reproduce the error:
```
def test_cam():
	model = models.densenet161(pretrained=True)
	path = 'PATH TO IMG'
	model.eval()
	image = Image.open(path).convert('RGB')
	transform_img = transforms.Compose([transforms.Resize([256,256]), transforms.ToTensor()])
	image = transform_img(image) 
	cam = GradCAMPlusPlus(model, model.features[-1], use_cuda=True)
	cam_mask = cam(input_tensor=image.unsqueeze(0))
	print('cam working')
```

Note this error is not occuring when using another layer i.e. model.features[-2] in model.features.

What am i doing wrong?

**Comment by jacobgil** [comment]
Hi, I noticed you might not be using the most up to date code
(In the up to date code you pass a list with the target_layers = [model.features[-1]].

Can you please pull and try again?
I couldn't reproduce this problem.

**Comment by chenhong73** [comment]
Can U tell how to fix this problem? Thank U.

**Comment by kopop8** [comment]
In the most up to date code, you should pass your target_layer like so: target_layers = [model.features[-1]] instead of how I did it initially.

**Comment by chenhong73** [comment]
> In the most up to date code, you should pass your target_layer like so: target_layers = [model.features[-1]] instead of how I did it initially.

Thanks a lot. I fixed it.
