### ISSUE TITLE
I want to get VGG16 [model.features[-2]] class activation map but there is some error

### ISSUE THREAD

**Issue by DJ-Maeng** [jacobgil/pytorch-grad-cam#148]
Hello. I want to get class activation map before MaxPool2d in VGG16.
So i setup target_layer = [model.features[-2]], but i got this error.

I think this problem caused register_full_backward_hook, but i don`t know how to solve this

RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.

I'd appreciate it if you could answer me.
Thank you

![image](https://user-images.githubusercontent.com/34765249/137624657-472974d6-61ea-4bcd-a387-e3a96367f27c.png)

**Comment by jacobgil** [comment]
Hi, I couldn't reproduce.
I need more details: which algorithm (e.g: grad cam)?
Can you paste the code snippet you used.
