### ISSUE TITLE
Did the Grad-Cam use the ReLU to get the finnal heatmap?

### ISSUE THREAD

**Issue by Mrwow** [jacobgil/pytorch-grad-cam#149]
Hi,
I read your code and want to confirm if the ReLU was applied in the CAM when I tried to use the Grad-Cam method.

In the function compute_cam_per_layer and get_cam_image in the base_cam.py, I didn't find code related to ReLU. Please let me know if I missed something here? Thanks a lot.

**Comment by Mrwow** [comment]
@jacobgil, Thank you for provide this clue. this line code does work like the ReLu. 
But here raises another question in the base_cam.py#L93 ~ L96, the sequence is like scale_cam_image, ReLU, Mean and then scale_cam_image again. 
Since the scale_cam_image already did the Min-Max scaling, the sequence is like Min-Max scaling, ReLU, Mean and Min-Max scaling.
I think the second Min-Max scaling is for coloration in the heat map, but why the first Min-Max scaling before ReLU and why Mean after ReLU?

**Comment by jacobgil** [comment]
Great, thanks!
