### ISSUE TITLE
use resnet

### ISSUE THREAD

**Issue by fahmanali** [jacobgil/pytorch-grad-cam#15]
Resnet model hasn't .features.
How I can use it using your code?

**Comment by AndrewSoul** [comment]
Similar to the question above~
If I trained a pytorch model without attribute features. How can I applied this method to my trained model?

**Comment by AndrewSoul** [comment]
> Resnet model hasn't .features.
> How I can use it using your code?

Maybe you can add the attribute features to the training code and train the Resnet model from scratch?

**Comment by Caoliangjie** [comment]
> Resnet model hasn't .features.
> How I can use it using your code?

Hi，fahmanali，I change the basic network from vgg19 to renset50 in the author’s basic code， there‘re really some differences between vgg19 and resnet50. You can fork from my repository if my code can help you.
My repository can be seen：https://github.com/Caoliangjie/pytorch-gradcam-resnet50

**Comment by Adarsh-Shrivastava-001** [comment]
I want to use the same code for resnet

But unable to do so

pls help

**Comment by loveunk** [comment]
@Adarsh-Shrivastava-001 
I have changed the original repo a little bit, and both vgg and resnet are supported now: https://github.com/loveunk/pytorch-grad-cam

**Comment by jdariasl** [comment]
@loveunk How do you define the target ? I understand the structure based on 'pre_features', 'features', 'classifier', but I'm still confused with the target: ['35'] for VGG and ['2'] for Resnet.

Thank you.

**Comment by frgfm** [comment]
@Adarsh-Shrivastava-001 @jacobgil if you're still having troubles, I'm maintaining a repo with many CAM method implementations. By default, the target layer is resolved automatically (the last one to produce tensors keeping the spatial dimensions), but you can specify any layer you wish.

I'd be glad to get some extra feedback!

**Comment by jacobgil** [comment]
Hi all,
In the updated repo there is support for all torchvision models, and also Vision Transformers.
Check the Readme :-)
