### ISSUE TITLE
Explainability heatmaps for multi output look very similar 

### ISSUE THREAD

**Issue by mhashas** [jacobgil/pytorch-grad-cam#163]
![338](https://user-images.githubusercontent.com/13119609/140022867-61855e7c-9e84-40c6-ae80-0a241e071af8.jpg)

I have used the trick that you mentioned of creating multiple SingleOutput models by returning x[task].

My network looks like this: Resnet18 -> tasks x linear layers 

Do you have any advice on what I could try to do?

**Comment by wbygit** [comment]
Yes, I find the same problem too.
I modified the code from Grad-CAM++ to adapt 1D ECG signal.
I use the output of Grad-CAM to visualize my ECG data.

My model is 1D-ResNet34 with CBAM module and target_layers is model.layer4[-1]. It's similar to the original ResNet34 model. And my task is a multi-label classification task.

There are results for two different  target_categories. It's more than similar. I calculate the difference of all results of different target_categories, the max difference is like 1e-6. 
![T改变](https://user-images.githubusercontent.com/35754856/140166809-d4c81843-9dc1-4242-a8b7-add8cb3afa1c.jpg)
![窦性心动过速](https://user-images.githubusercontent.com/35754856/140166818-41faa167-ce6a-4d2c-8d63-7a79f9c789fb.jpg)

**Comment by jacobgil** [comment]
I think we need to distinguish between two possibilities:
- These different tasks are utilizing similar locations in the image.
- There is a bug in the code somewhere.

I think if we can try this, it will help debug:
- Can you save the grayscale cam mask (in the range 0-1), multiply the image by it, so only the high scoring areas are kept, and then run the model on the new image?
Are the scores of all the categories still high or are they low now?

- Can you please try the other models, like ScoreCAM and AblationCAM, do they get similar results?

**Comment by wbygit** [comment]
> Yes, I find the same problem too. I modified the code from Grad-CAM++ to adapt 1D ECG signal. I use the output of Grad-CAM to visualize my ECG data.
> 
> My model is 1D-ResNet34 with CBAM module and target_layers is model.layer4[-1]. It's similar to the original ResNet34 model. And my task is a multi-label classification task.
> 
> There are results for two different target_categories. It's more than similar. I calculate the difference of all results of different target_categories, the max difference is like 1e-6. 

I have solved this problem because I find that my modification for 1D data is wrong. After correcting mistakes, it works well.
Here are the current results for two different target_categories. Hope @mhashas you can find some code bugs too.

![resnet34_cbam  layer4 -1  在 1661089 xml 数据上对 室性早搏(TP) 类别的注意力热力图 Grad-CAMpp-V1](https://user-images.githubusercontent.com/35754856/142365735-487f4594-6067-4d7b-9f39-7719fccdf4b6.jpg)
![resnet34_cbam  layer4 -1  在 1661089 xml 数据上对 T改变（低平，双向 倒置 深倒置，浅倒置，切迹）(TP) 类别的注意力热力图 Grad-CAMpp-V1](https://user-images.githubusercontent.com/35754856/142365946-5655d10d-5cfc-4604-ae50-f48a45993876.jpg)

**Comment by jacobgil** [comment]
Great.
Closing for now, please re-open if still relevant.

**Comment by mhashas** [comment]
@jacobgil 

The problem for me was setting eigen_smooth to True. Setting it to False solves the issue

**Comment by philippkiesling** [comment]
@mhashas It is the same for me. 
I also noted that the smoothed areas are not similar to the originally found areas as illustrated in the images

eigen_smooth = True: 
![smoothed](https://user-images.githubusercontent.com/65088541/165047160-adaede25-fc57-42ea-a00b-ffb197f33854.png)

eigen_smooth = False: 
![unsmoothed](https://user-images.githubusercontent.com/65088541/165047271-fc4664f8-1aa9-4626-8e04-890caf085257.png)
