### ISSUE TITLE
Combining Grad-CAM with Guided Backpropagation

### ISSUE THREAD

**Issue by Mshz2** [jacobgil/pytorch-grad-cam#166]
Hi,

In the Readme you have shown the result of Combining Grad-CAM with Guided Backpropagation for the pug dog class.
May I please as for the help how can I do the same in [these ](https://github.com/jacobgil/pytorch-grad-cam#using-from-code-as-a-library) lines?

`cam = GradCAM(model=model, target_layers=target_layers, use_cuda=args.use_cuda)`
`grayscale_cam = cam(input_tensor=input_tensor, target_category=target_category)`

**Comment by jacobgil** [comment]
Hello,
You have an example here:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/cam.py#L125
