### ISSUE TITLE
Problem about VIT_CAM generate

### ISSUE THREAD

**Issue by niupapachina** [jacobgil/pytorch-grad-cam#168]
Dear author 

Thank you very much for your contribution！
but the mask I generated using your **vit_cam model** does not work well. 
This mask cannot focus on objects (but the classification accuracy is very high at 97%), 
so I would like to ask you what the problem is？
(![xgradcam_cam](https://user-images.githubusercontent.com/56630281/141221237-d4eef4b3-05ac-45b7-a2f8-5501b5232ba5.jpg))](url)
Thank you!

**Comment by jacobgil** [comment]
Hello,
For VIT it often needs tuning.
Can you share more details to help understand:
1. The algorigm (e.g gradcam, ablation cam? )
2. The target layer?
