### ISSUE TITLE
Can GradCam work for the model output like [1,64,5,5]?

### ISSUE THREAD

**Issue by huangxilang901** [jacobgil/pytorch-grad-cam#169]
Thank you for your excellent work!

I can visualize the GradCam for the model output size of [1, 1000] (i.e., using Resnet-18). But my own model dose not include a fully connected-layer in the end. For example, the output size is [1, 64, 5, 5] (batch, channel, height, width). Could you please guide me how to modify the code? 

Thank you in advance.

**Comment by jacobgil** [comment]
Hi,
Yes.
You will need to modify the get_loss function in base_cam.py:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/base_cam.py#L40
To perform your custom logic and implement the target you want to visualize.
For example, do you want to take the middle pixel, or maybe an average on the pixels, or something else?
