### ISSUE TITLE
target_layers = [model.xxx[x]]

### ISSUE THREAD

**Issue by ldlshizhu** [jacobgil/pytorch-grad-cam#172]
could you please tell me how to print 'target_layers = [model.xxx[x]]'vector?
I've been reporting mistakes  ：
 File "cam.py", line 105, in <module>
    target_layers = [model.bias[-1]]
AttributeError: 'str' object has no attribute 'bias'
Thank you very much.

**Comment by ldlshizhu** [comment]
My model file is 'XXXX.h5' or 'XXX.pth', and I used
content = torch.load('last_fpn.h5')
print(content.keys())
for key, value in content["model"].items():
    print(key, value.size(), sep="   ")

it print like:
module.smooth2.1.num_batches_tracked   torch.Size([])
module.final.weight   torch.Size([3, 64, 3, 3])
...

**Comment by jacobgil** [comment]
Hi, target_layers needs to have actual layers from the models, and not strings.

If you want to iterate over the model,
you can do:

```python
for name, layer in model._modules.items():
    print(name, layer)
```
And then choose target_layers =[layer] for one of the layers of your choice.
