### ISSUE TITLE
one TypeError

### ISSUE THREAD

**Issue by fsted** [jacobgil/pytorch-grad-cam#174]
Hi,thanks for the great code,but when i use it as library, it found a Error：

Exception ignored in: <function BaseCAM.__del__ at 0x0000023FF383A6A8>
Traceback (most recent call last):
  File ".\lib\site-packages\pytorch_grad_cam\base_cam.py", line 192, in __del__
    self.activations_and_grads.release()
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'
Traceback (most recent call last):
  File "./test.py", line 46, in <module>
    cam = GradCAM(model=model, target_layer=target_layer, use_cuda=False)
TypeError: __init__() got an unexpected keyword argument 'target_layer'

my code is same as your frist example of library;what should i do? thanks :）

**Comment by fsted** [comment]
I know, the example has a little wrong:
`cam = GradCAM(model=model, target_layers=target_layer, use_cuda=False)`

**Comment by kqdhx** [comment]
loss a "s"  be "target_layers" not is "target_layer"
