### ISSUE TITLE
About uses_gradients attribute in the __init__ of BaseCAM

### ISSUE THREAD

**Issue by wxr5899** [jacobgil/pytorch-grad-cam#175]
Thank you for your excellent work! The code style is really friendly. But I still have the following problems about the `uses_gradients` attribute in the `__init__` of `BaseCAM`:
What is the function of computing the loss? 
Whether there is any impact if I set the  `uses_gradients = False`.

**Comment by zhanjiahui** [comment]
same question!

**Comment by wxr5899** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jacobgil** [comment]
Hi,
Some methods, like "Ablation CAM" and "Score CAM" are gradient free.
So we can skip the back-prop for those methods.
And for them we set uses_gradients = False.

Other methods, like Grad-CAM, need the gradients.

**Comment by wxr5899** [comment]
Thank you, I understand!
