### ISSUE TITLE
could it apply to segmentation tasks?

### ISSUE THREAD

**Issue by q671383789** [jacobgil/pytorch-grad-cam#177]
if thers is a model like resnet50 with Fpn_Head, if I want to use cam for it 
I have to create another model resnet50 and with a fc_linear?
becuase the model for cam must output like [bs, num_classes] not [bs, num_classes, h , w]?

**Comment by jacobgil** [comment]
For classification, pixel attribution methods show what regions where important for the classification the image.

For segmentation, you have to redefine the task.
Some options would be:
1. Show what's important for the classification of the middles pixel in the image ( or any other pixel you chose).

In this case, you could define a model wrapper that converts the segmentation model into a classification model,
e.g by
```
output = segmentation_output[:, :, h//2, w//2]]
```

2. Take all of the pixels that belong to some region, and show what was important for them.

**Comment by jacobgil** [comment]
Hi,
I'm happy to share that now we have a detailed notebook about how to apply this to semantic segmentation:
[](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Semantic%20Segmentation.ipynb)

**Comment by q671383789** [comment]
@jacobgil  Thanks for ur great work! actually I have made it work on segmentation work according to another issue #109 
Thanks again
