### ISSUE TITLE
Support of Batch Input

### ISSUE THREAD

**Issue by CielAl** [jacobgil/pytorch-grad-cam#18]
Hi, 

it appears that the original code did not directly support the batch input. I forked the repo and created some simple modification. (you may discard the part to load my own models)
https://github.com/CielAl/pytorch-grad-cam_batch/blob/master/grad_cam.py#L114

Hope this might be useful in case others try to apply your implementation :)))

**Comment by amands97** [comment]
Thanks for providing this implementation!

**Comment by gwang-kim** [comment]
Excuse me, can your algorithm generate 4 gradcam image given 4 batches of input? I really need this algorithm for resnet. But your algoritm is based on VGG. So I want to modify your algorithm for Resnet. Can you tell me the keypoint  how to generate batch gradcam?

**Comment by gwang-kim** [comment]
Thank you!

**Comment by CCYChongyanChen** [comment]
> Hi,
> 
> it appears that the original code did not directly support the batch input. I forked the repo and created some simple modification. (you may discard the part to load my own models)
> https://github.com/CielAl/pytorch-grad-cam_batch/blob/master/grad_cam.py#L114
> 
> Hope this might be useful in case others try to apply your implementation :)))

Thanks for providing the implementation. 
Would you mind sharing the code of the main function, which is deleted in your repo. (how you read images in batch and what is the batch size?) 

Thanks a lot!

**Comment by jacobgil** [comment]
I am happy to say that now all methods fully support batches.
Please see the Readme for more details.
