### ISSUE TITLE
Add a conda installation option

### ISSUE THREAD

**Issue by sugatoray** [jacobgil/pytorch-grad-cam#180]
Adding a conda installation option could be very helpful. I have started working on a PR (https://github.com/conda-forge/staged-recipes/pull/17244) already to add `grad-cam` from PyPI to conda-forge channel. Once the PR is merged, `grad-cam` could be installed as follows.

```sh
conda install -c conda-forge grad-cam
```

> :bulb: I will open a PR here to update the install instructions, once `grad-cam` is available on conda-forge channel.

**Comment by sugatoray** [comment]
cc: @jacobgil

**Comment by jacobgil** [comment]
This is Awesome!!

**Comment by sugatoray** [comment]
@jacobgil Could you please take a look at bothe of the following two files and confirm that the list of packages under `install_requires` is the bare minimum required to install the library and the additional ones in `requirements.txt` are not necessary for installing it? If so, are the additional libraries optional?

- Source: [`setup.py:install_requires` vs. `requirements.txt`](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/)

  ![image](https://user-images.githubusercontent.com/10201242/146629257-7cc80939-aa68-4690-9047-6c112cd424bc.png)

- Reference: [Stackoverflow: `setup.py:install_requires` vs. `requirements.txt`](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py)

- `setup.py:install_requires` vs. `requirements.txt` in `grad-cam`:

  | https://github.com/jacobgil/pytorch-grad-cam/blob/770f29027598a8bf3ef660e04d14c44770b4d03c/requirements.txt#L1-L8 | https://github.com/jacobgil/pytorch-grad-cam/blob/770f29027598a8bf3ef660e04d14c44770b4d03c/setup.py#L25-L32 |
  |:---:|:---:|
  | `requirements.txt` | `setup.py:install_requires` |

**Comment by sugatoray** [comment]
Hi @jacobgil, 

## A question for you

> when you pip install this library, which libraries are installed? The ones mentioned in `setup.py:install_requires` + their dependencies **OR**, the list of libraries in `requirements.txt` + their dependencies?

**Comment by jacobgil** [comment]
Good point, I think there is un-necessary duplication here.
We should remove the install_requires and use only requirements.txt.

I think we should modify setup.py to do

```python
with open('requirements.txt') as f:
    required = f.read().splitlines()
...
install_requires = required
```

**Comment by sugatoray** [comment]
@jacobgil You might want to see the implementation [here]([#dimcli-setup.py]) (but also add `requirements.txt` to MANIFEST.in if not done so already).

[#dimcli-setup.py]: https://github.com/digital-science/dimcli/issues/74#issuecomment-997203674

- https://github.com/digital-science/dimcli/issues/74#issuecomment-997203674

- https://github.com/digital-science/dimcli/blob/36382e2933ece95baa02220f119da31c03f455f9/setup.py#L36-L44

[![image](https://user-images.githubusercontent.com/10201242/146838581-959818b4-acac-4ff4-a256-915cdb6229df.png)][#dimcli-setup.py]

**Comment by sugatoray** [comment]
@jacobgil `grad-cam` is now available on conda-forge. :rocket:

**Comment by sugatoray** [comment]
Update: `grad-cam` was just rendered on conda-forge. You should be able able to install it with conda in 2-3 hours.

![image](https://user-images.githubusercontent.com/10201242/146843754-750505d4-3b3e-4328-8916-8d9ab1236886.png)

**Comment by jacobgil** [comment]
Thanks.

I also updated the master branch so it uses requirements.txt in setup.py.

**Comment by jacobgil** [comment]
How can we push new versions to conda-forge?

**Comment by sugatoray** [comment]
> How can we push new versions to conda-forge?

## Process to raise a PR for conda-forge package update

- **Step-1**: Go to: https://github.com/conda-forge/grad-cam-feedstock
- **Step-2**: Fork it. Create a new branch (for example: `update_v1.2.3` to update some library to it's version `1.2.3`).
- **Step-3**: Update the `recipe/meta.yaml`.
  - [x] Update the jinja2 variable: `version` (same as PyPI)
  - [x] Update the field: `sha256` (should be same as PyPI source, `<package>.tar.gz` file)
  - [x] If changing the version, DON'T UPDATE the build number. 
  - [x] If making a change to the recipe, without any version update, increase the build number by 1.
  - [x] Update the dependencies under run-requirements (these are the ones you typically include in `setup.py`/ `requirements.txt`).
    - [x] add newer dependencies (they must exist on conda-forge channel, if not speak with me)
    - [x] update version specification for each dependency
    - [x] use the more classical `>`, `=`, `<` for defining version constraints instead of `^`, `~`.
    - [x] drop dependencies that are no longer included in your `setup.py` 
    - [x] NOTE: optional dependencies should be dropped here, so users can install them only if they need them. Ideally, such optional dependencies should be made part of `extras` under `setup.py`.
- **Step-4**: Submit a PR (follow the instructions while opening the PR).
- **Step-5**: Review
  - [x] If all CI's have passed (`pytorch` is not available on conda-forge for windows, so, typically the windows CI run will fail, and that is okay), then we move to merging.
  - [x] I will review and once all looks good will merge it.
- **Step-6**: Once merged, the new package will be available on the channel in 2-3 hours.

**Comment by sugatoray** [comment]
> I also updated the master branch so it uses requirements.txt in setup.py.

So, once you make the next PyPI update, please let me know. The conda-forge recipe would need some changes to match the new `setup.py:install_requires`.

**Comment by jacobgil** [comment]
Thanks, The PyPI version was updated with the new changes.

**Comment by sugatoray** [comment]
Great. So, do you want to make the changes to the recipe file?

Btw, here is [LinkedIn post](https://www.linkedin.com/posts/sugatoray_xai-python-pytorch-activity-6879014206507683840-ViPG) I made on the availability of `grad-cam` on conda-forge.

**Comment by sugatoray** [comment]
What is the latest version? `v1.3.5` or `v1.3.6`?

**Comment by jacobgil** [comment]
It's on PyPI now. The version is 1.3.6. Usually it shows the latest package immediately.

**Comment by jacobgil** [comment]
I will try making a PR for the recipe with the latest change, this will take me ~a few days to get to it.

**Comment by jacobgil** [comment]
This is great, thanks a lot for your contribution.
Going to see how to add a github readme download counter for conda as well :-)

**Comment by sugatoray** [comment]
@jacobgil I updated the recipe myself this time, since you are now reading in the `setup.py:install_requires` from `requirements.txt`. Please take a look at the PR in the feedstock repository, to give you an idea of what was done this time. If your dependencies don't change, in future releases, you would only have to update the `version` and the `sha256` from PyPI.
