### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by allenlittlestar** [jacobgil/pytorch-grad-cam#182]
Hello, I have the following problem
 “
base_cam.py", line 134, in aggregate_multi_layers
  cam_per_target_layer = np.concatenate(cam_per_target_layer, axis=1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate” 
when reproducing your code. Is it with grad_ About the cam version, or Python and python versions, would you please help me provide some suggestions to solve the problem? Thank you very much.

**Comment by alshenoudy** [comment]
I have a similar issue, haven't solved it yet. But tracing this the `aggregate_multi_layers` function is receiving an empty object, and hence numpy can't perform ``np.concatenate` on an empty array.

If I find a solution, I'll post it in this thread.

**Comment by alshenoudy** [comment]
@allenlittlestar I had a similar issue when I was using a modified ResNet50 to my use-case of specific classes. 

Tracing this, apparently `np.concatenate()` was receiving an empty array. Making sure that my entire network gradients are not freezed solved this issue.

**Comment by jacobgil** [comment]
Hi,
Indeed what @alshenoudy said.

To see if it's because of the gradients, you can also try switching to one of the non gradient methods, ScoreCAM or AblationCAM, and see if this happens.
