### ISSUE TITLE
Suggestion to add Zoom-CAM

### ISSUE THREAD

**Issue by plthon** [jacobgil/pytorch-grad-cam#184]
Full paper: https://ieeexplore.ieee.org/abstract/document/9412980
GitHub Repo: https://github.com/X-Shi/Zoom-CAM

Hi, I would like to suggest the addition of Zoom-CAM into this library. From the paper, the visualizations provided look promising.

**Comment by jacobgil** [comment]
Thank you for the suggestion.
Will try adding this in the future - but a PR will be very welcome !
