### ISSUE TITLE
RuntimeError while using a different CNN model

### ISSUE THREAD

**Issue by AnjanaSamindraPerera** [jacobgil/pytorch-grad-cam#185]
Instead of using the given models I used  xception network. But doing so it gives ,

`RuntimeError: Output 0 of BackwardHookFunctionBackward is a view and is being modified inplace. This view was created inside a custom Function (or because an input was returned as-is) and the autograd logic to handle view+inplace would override the custom backward associated with the custom Function, leading to incorrect gradients. This behavior is forbidden. You can remove this warning by cloning the output of the custom Function.`

What might be the reason. Is n't this compatible with other models?

**Comment by jacobgil** [comment]
Hi,
The recent version should fix this.
Can you please try to upgrade with `pip install --upgrade grad-cam`, or git pull the latest version?

**Comment by AnjanaSamindraPerera** [comment]
I clone the repo yesterday though.

**Comment by AnjanaSamindraPerera** [comment]
Upgrading gradcam fixed it. This is another issue I came across.

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x6400 and 1024x16)`

**Comment by jacobgil** [comment]
Hi,
I need more details to try help understand the error.
What's the input tensor shape to the network?
Any other details you can share?

**Comment by AnjanaSamindraPerera** [comment]
Managed to run the code after changing the input tensor shape. Specifically the image size. I wonder is there some way to create a gif to visualize what happened to the image in each layer.

**Comment by jacobgil** [comment]
One way would be to create the CAM multiply times, each time for a different layer.
Currently there is no "built in" way of doing it in one call.
