### ISSUE TITLE
element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by EatonL** [jacobgil/pytorch-grad-cam#187]
When I learned your example to write code, my code did report such an error at runtime:

**RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn**

How should we solve this problem？

**Comment by jacobgil** [comment]
Hello,
Can you please paste the code you used here?

**Comment by EatonL** [comment]
```
    resnet = torchvision.models.resnet152(pretrained=False)
    resnet.fc = torch.nn.Linear(2048, 23)

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    weights_path = 'weights'
    model = resnet

    model.load_state_dict(torch.load(os.path.join(weights_path, '79bestModel.pth'))['net'])
    model.eval()
    cam = GradCAM(model=model, target_layers=[model.layer4[-1]], use_cuda=True)

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=args.lr,
                          momentum=0.9, weight_decay=5e-4)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=20)

    imgs = glob.glob(os.path.join(inputpath,'*.png'))
    with torch.no_grad():
        for i,img in enumerate(imgs):
            img_ori = cv2.imread(os.path.join(inputpath,img),1)[:, :, ::-1]
            # img_ori = cv2.resize(img_ori, (224, 224))
            img_ori = np.float32(img_ori) / 255
            input_tensor = preprocess_image(img_ori, mean=[0.5, 0.5, 0.5],
                                            std=[0.5, 0.5, 0.5])

            grayscale_cam = cam(input_tensor=input_tensor, eigen_smooth=True)
            grayscale_cam = grayscale_cam[0, :]
            visualization = show_cam_on_image(img_ori, grayscale_cam, use_rgb=True)

```
These are my codes

**Comment by jacobgil** [comment]
I'm not able to reproduce this error so far.

Can you please check:
1. If you're using the latest version?
2. What's the pytorch version you're using?

**Comment by EatonL** [comment]
the version of the grad-cam i am using is 1.3.7,and pytorch is 1.9.0

**Comment by SteamerLee** [comment]
I have the same problem but now it has been solved. It may be caused by  "with torch.no_grad()" which stops the tracking of gradients so that there is no gradient information passed to grad cam.

**Comment by EatonL** [comment]
> I have the same problem but now it has been solved. It may be caused by "with torch.no_grad()" which stops the tracking of gradients so that there is no gradient information passed to grad cam.


I tried what you said. It's really effective. Thank you

**Comment by EatonL** [comment]
> I have the same problem, here is my code snippet:
> 
> ```
> import torch    
> import cv2
> import numpy as np
> import requests
> import torchvision.transforms as transforms
> from pytorch_grad_cam import EigenCAM
> 
> response = requests.get("https://i.imgur.com/ExdKOOz.png")
> file = open("sample_image.png", "wb")
> file.write(response.content)
> file.close()
> 
> img_ori = cv2.imread("sample_image.png",1)[:, :, ::-1]
> img_ori = cv2.resize(img_ori, (640, 640))
> img_ori = np.float32(img_ori) / 255
> 
> transform = transforms.ToTensor()
> # Convert the image to PyTorch tensor
> tensor = transform(img_ori).unsqueeze(0)
> 
> model = torch.hub.load('ultralytics/yolov5', 'yolov5s')
> model.eval()
> 
> 
> target_layers = [model.model.model.model[0]]
> cam = EigenCAM(model, target_layers, use_cuda=False)
> 
> grayscale_cam = cam(tensor)
> ```
> 
> Do you have any suggestions on how to solve it?
> 
> When I remove: '
> 
> ```
>         if self.uses_gradients:
>             self.model.zero_grad()
>             loss = sum([target(output) for target, output in zip(targets, outputs)])
>             loss.backward(retain_graph=True)
> ```
> 
> from: `https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/base_cam.py`

You can look at @SteamerLee 's answer.It's really useful.
And I read your code. I didn't find out what your problem is. I'm sorry

**Comment by jacobgil** [comment]
Dear all,
I added a notebook with a full example of how to use this library for YOLO5.
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/EigenCAM%20for%20YOLO5.ipynb

The bug you got above was that EigenCAM was computing gradients, although it's a gradient free method.
It's constructor now passes uses_gradients=False.

It should work now (also published a new version to pypi).

**Comment by Audrey528** [comment]
@jacobgil I run [](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/EigenCAM%20for%20YOLO5.ipynb). EigenCAM have the same question.

**Comment by Audrey528** [comment]
@jacobgil I run like the file of YOLO5, but when I run EigenCAM,  I meet the same question.

**Comment by vijayshgupta** [comment]
pls update the code, its not working

**Comment by deep-matter** [comment]
is the easiest way to solve this problem is by using 
```pyhon
with torch.enable_grad():
## here the gradient are trackable
```
