### ISSUE TITLE
RuntimeError: Could not infer dtype of SemanticSegmentationTarget

### ISSUE THREAD

**Issue by q671383789** [jacobgil/pytorch-grad-cam#190]
I tried cam for segmentation tasks according to tutorials on my own dataset, but I got this.while fomer solution is work for former version of codes #107 , is there any different between this two types of codes on the theory, or just the new one have a compatible feature for segmentation task

**Comment by jacobgil** [comment]
Hi,
The segmentation task will work only with the newest version of the code, it won't work with the previous versions since there was a major refactoring to support it.

Are you using the newest version of the code?

**Comment by q671383789** [comment]
hey, thanks for replying so fast, I'm using the newest one. But before this version, the previous one I also worked using #107 mothed u mentioned. But the newest one i meet with this error 
![image](https://user-images.githubusercontent.com/48686306/148049287-61df9d57-be27-4cc7-bcf8-76a61e00a5e6.png)

**Comment by jacobgil** [comment]
Hi,
Can you past the code, how are you creating the CAM and then calling it?
Are you using the latest code from git or something else?

**Comment by q671383789** [comment]
`    with cam_algorithm(model=model,
                       target_layers=target_layers,
                       use_cuda=args.use_cuda) as cam:
        for idx, (img, mask, rgb_img, image_name) in enumerate(data):
        # AblationCAM and ScoreCAM have batched implementations.
        # You can override the internal batch size for faster computation.
            cam.batch_size = 1
            input_tensor = img.unsqueeze(0).cuda()
            pred = model(img.unsqueeze(0).cuda())  ## pred: 1,2,512,512
            # size = mask.shape[-2]
            # pred = F.interpolate(pred, size, mode='bilinear', align_corners=False)
            normalized_mask = F.softmax(pred, dim=1).cpu()
            pred_mask = normalized_mask[0, :, :, :].argmax(0).detach().cpu().numpy()
            pred_mask_uint8 = 255 * np.uint8(pred_mask == targets_idx)
            pred_mask_float = np.float32(pred_mask == targets_idx)
            targets = [SemanticSegmentationTarget(targets_idx, pred_mask_float)]

            grayscale_cam = cam(input_tensor=input_tensor,
                                targets=targets,
                                aug_smooth=args.aug_smooth,
                                eigen_smooth=args.eigen_smooth)
            # Here grayscale_cam has only one image in the batch
            grayscale_cam = grayscale_cam[0, :]
            rgb_img = np.array(rgb_img)
            rgb_img = np.float32(rgb_img) / 255.0
            cam_image = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)
            cam_image = cv2.cvtColor(cam_image, cv2.COLOR_RGB2BGR)

            cv2.imwrite('vis_res/'+str(idx)+f'{args.method}_cam.jpg', cam_image)`
I have made a mistake and fix it, now it can be run, but the answer seems not correct, I have to check more, but thanks.  but I still want to the method in #107 is correct or not? I have use it successfully

**Comment by q671383789** [comment]
![0gradcam_cam](https://user-images.githubusercontent.com/48686306/148172693-6b0b9e57-f94f-4725-8b94-89bba4054e36.jpg)
![0gradcam_cam](https://user-images.githubusercontent.com/48686306/148172714-41b755c2-97dc-47cd-8920-62d32783b1ba.jpg)
Maybe its something with my model，the first pic is a former model, it works well, the latter pic is a new model, they have almost no differences ,and are both using resnet50 as backbone for segmentation, I don't know why, maybe the latter one just cant be good perform on cam. But thanks a lot.
