### ISSUE TITLE
Thermal maps obtained by different methods vary greatly

### ISSUE THREAD

**Issue by onion-rain** [jacobgil/pytorch-grad-cam#191]
Is this phenomenon correct? 
I used usage_examples/vit_example.py to test the thermal maps for different methods. The results are as follows
![image](https://user-images.githubusercontent.com/40513765/148039352-bf1fbe09-1eba-4a87-b578-e7f42873296e.png)

**Comment by jacobgil** [comment]
This this can happen.
For transformers I noticed that generally gradient free methods: "ScoreCAM", "AblationCAM" perform well.

**Comment by onion-rain** [comment]
Could you please explain why the gradient method does not perform well?

**Comment by onion-rain** [comment]
This may be the reason(quote from "Ablation-CAM: Visual translation for Deep Convolutional Network via gradient-free Localization"), transformer has many full connect layers, resulting in poor performance of gradient-based methods

![image](https://user-images.githubusercontent.com/40513765/149442831-d0a81c8d-eff4-4d58-8d80-26f5770e0ae0.png)
![image](https://user-images.githubusercontent.com/40513765/149442787-9a2b3d6c-2562-4484-808d-403b1a61866d.png)
![image](https://user-images.githubusercontent.com/40513765/149442802-a1a1eaa6-9c13-4f98-b58b-4601f7c7f69b.png)
