### ISSUE TITLE
ScoreCAM empty cam_per_layer

### ISSUE THREAD

**Issue by ericotjo001** [jacobgil/pytorch-grad-cam#194]
In ScoreCAM implementation, if we set target_layers, we get warning "Warning: You are using ScoreCAM with target layers, however ScoreCAM will ignore them". But when we call it with target_layers=[], the resulting cam_per_layer is of course empty, and this raises error with aggregate_multi_layers(cam_per_layer).

**Comment by jacobgil** [comment]
Thanks for reporting this.

Yes, it's a bug - score cam should work without target layers.
Need a PR to fix this.
In the meanwhile I think you can pass a dummy value in target_layers.

**Comment by ericotjo001** [comment]
Thanks for the response. I will avoid it for now.

**Comment by SelfAttention** [comment]
Hi
I got this problem too,how can i solve this problem sepcificly?

**Comment by SelfAttention** [comment]
Hi
I got this problem too,how can i solve this problem specificly?
