### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'targets'

### ISSUE THREAD

**Issue by LCA-0907** [jacobgil/pytorch-grad-cam#196]
Hello,
I'm trying to use grad-cam on semantic segmentation work and encountered 
```
Traceback (most recent call last):
    File "segment.py", line 74, in <module>
        targets=targets)[0, :]
TypeError: __call__() got an unexpected keyword argument 'targets'
```

I think I followed the tutorial step by step and have no idea about this error, could any one help me?
Below is my code.

`model = deeplabv3_resnet50(pretrained=True, progress=False)
    model = model.eval()
    if torch.cuda.is_available():
        model = model.cuda()
        input_tensor = input_tensor.cuda()

    output = model(input_tensor)
    output_mask = output['out']
    
    normalized_masks = torch.nn.functional.softmax(output_mask, dim=1).cpu()
    category = sem_class_to_idx["person"]
    mask = normalized_masks[0, :, :, :].argmax(axis=0).detach().cpu().numpy()
    np.set_printoptions(threshold=np.inf)
   
    mask_uint8 = 255 * np.uint8(mask == category)
    mask_float = np.float32(mask == category)
    outimg = np.repeat(mask_uint8[:, :, None], 3, axis=-1)
    
    class SemanticSegmentationTarget:
        def __init__(self, category, mask):
            self.category = category
            self.mask = torch.from_numpy(mask)
            if torch.cuda.is_available():
                self.mask = self.mask.cuda()
            torch.set_printoptions(profile="full")
            
        def __call__(self, model_output):
            return (model_output[self.category, :, : ] * self.mask).sum()
    
    target_layers = [model.backbone.layer4]
    targets = SemanticSegmentationTarget(category, mask_float)

    with GradCAM(model=model,
                target_layers=target_layers,
                use_cuda=torch.cuda.is_available()) as cam:
        grayscale_cam = cam(input_tensor=input_tensor,
                            targets=targets)[0, :]
        cam_image = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)`

**Comment by jacobgil** [comment]
Hi, what version is gradcam here?
Is there a chance you're using an earlier version (before the api change) ?
Can you please try doing a pip install upgrade, or pulling the latest git code?

**Comment by LCA-0907** [comment]
Ok, after reinstall gradcam, I can run the tutorial code with no error now.
Thank you very much.

**Comment by wang1066828636** [comment]
hello,i want the gradcam version , thanks
