### ISSUE TITLE
Number of output channels is not the same with input

### ISSUE THREAD

**Issue by behnazelhaminia** [jacobgil/pytorch-grad-cam#197]
Thank you for your code. My input is [1,3,16,112,112] (C3D video action detection network), and the each video is [16,112,112]. But my output is [7,112,112]. I am not able to have attention map for each frame of video. Any idea where is my mistake?

**Comment by jacobgil** [comment]
I would start from feeding every 112x112 frame seperately into the network, and making sure the CAM makes sense.
