### ISSUE TITLE
Bug when using a mixed precision model: src data type = 23 is not supported

### ISSUE THREAD

**Issue by ymp5078** [jacobgil/pytorch-grad-cam#198]
_line 57, in scale_cam_image
    img = cv2.resize(img, target_size)
cv2.error: OpenCV(4.5.4-dev) :-1: error: (-5:Bad argument) in function 'resize'
\> Overload resolution failed:
\>  - src data type = 23 is not supported
\>  - Expected Ptr<cv::UMat> for argument 'src'_

**The following code produce the above error when using a mixed precision model**

```
def scale_cam_image(cam, target_size=None):
    result = []
    for img in cam:
        img = img - np.min(img)
        img = img / (1e-7 + np.max(img))
        if target_size is not None:
            img = cv2.resize(img, target_size)
        result.append(img)
    result = np.float32(result)

    return result
```

`cv2.resize` does not support float16.

suggested change:
```
def scale_cam_image(cam, target_size=None):
    result = []
    for img in cam:
        img = img - np.min(img)
        img = img / (1e-7 + np.max(img))
        if target_size is not None:
            img = cv2.resize(img.astype(np.float32), target_size)
        result.append(img)
    result = np.float32(result)

    return result
```

Please take a look and see if it make sense

**Comment by mZhenz** [comment]
I got the same problem with you.

**Comment by mZhenz** [comment]
I find it can be easily fixed by changing the mixed precision model to a float32 one by model.float().

**Comment by ymp5078** [comment]
agree with @mZhenz. The easy fix is just to change the source code as I suggested or use your work around. The 'cam' variable passed in is not controlled by the used thus I suggest a bug fix.
