### ISSUE TITLE
Why use target_layer_names = ["35"]  rather than "34" or something else ? 

### ISSUE THREAD

**Issue by Captainzj** [jacobgil/pytorch-grad-cam#20]
why not  use target_layer_names = ["34"] ?  I need to use Densenet, I set target_layer_names = ["norm5"].  I don't know  if this is reasonable.
Your help is very important to me. I hope to receive your reply.

**Comment by gokriznastic** [comment]
@Captainzj how did you adapt it for densenet121?

**Comment by TheMemoryDealer** [comment]
Now supports DenseNet, just do
target_layer = model.features[-1]

as explained in https://github.com/jacobgil/pytorch-grad-cam/issues/26#issuecomment-826504086
