### ISSUE TITLE
Reproducibility Issues

### ISSUE THREAD

**Issue by canerozer** [jacobgil/pytorch-grad-cam#203]
Hello,

Thanks for creating this repository. I'm trying to reproduce the results for 'both.jpg' by using ViT and SwinT, but I'm experiencing some bugs that are related with the version of the codebase. Can you provide some additional information to make it run on Google Colab?

Here is my baseline notebook for your access: https://colab.research.google.com/drive/1UXWDnFlsHf8suNugFHWvuh6boP9jb4IS?usp=sharing

Thank you.

**Comment by jacobgil** [comment]
Hello, sorry for the late reply.
Can you please git pull and try again? This is supposed to be fixed now.
