### ISSUE TITLE
picture resize 384*384 with swin-transformer-base

### ISSUE THREAD

**Issue by zxm111222333** [jacobgil/pytorch-grad-cam#204]
Your code is very useful for me ,thanks!
But, now I want to resize picture to 384*384, use swin-transformer-base(swin_base_patch4_window7_224_22kto1k.pth) to watch the picture's effect of feature visualization reslut.
How should I change your code?

**Comment by jacobgil** [comment]
Hi,
Sorry for the very late reply.

Can you please clarify what you mean, swin-transformer-base expects 224x224, no?

In any case, I think nothing is supposed to change in the code in this case. What error are you getting ?
