### ISSUE TITLE
Question About 'GuidedBackpropReLUModel'

### ISSUE THREAD

**Issue by Captainzj** [jacobgil/pytorch-grad-cam#21]
https://github.com/jacobgil/pytorch-grad-cam/blob/master/grad-cam.py  # 176
```
one_hot.backward(retain_variables=True)  # not used 
```
'gb.jpg' and 'cam_gb.jpg' are both noise image.

**Comment by doublemanyu** [comment]
Hey man, did you solve the question? I met the same problem with you

**Comment by doublemanyu** [comment]
> https://github.com/jacobgil/pytorch-grad-cam/blob/master/grad-cam.py # 176
> 
> ```
> one_hot.backward(retain_variables=True)  # not used 
> ```
> 
> 'gb.jpg' and 'cam_gb.jpg' are both noise image.

Hey man, did you solve the question? I met the same problem with you

**Comment by LiamTTT** [comment]
> 
> 
> > https://github.com/jacobgil/pytorch-grad-cam/blob/master/grad-cam.py # 176
> > ```
> > one_hot.backward(retain_variables=True)  # not used 
> > ```
> > 
> > 
> > 'gb.jpg' and 'cam_gb.jpg' are both noise image.
> 
> Hey man, did you solve the question? I met the same problem with you

I met the same problem with you guys too. One posible solution is replacing 'retain_variables' by 'retain_graph'. In recent pytorch version, 'retain_variables' was replaced by 'retain_graph'. 
Hope useful.
