### ISSUE TITLE
Hook doesn't work in layers of subclass of vision transformer

### ISSUE THREAD

**Issue by ycl54** [jacobgil/pytorch-grad-cam#211]
In my code implementation, vision transformer in encapsulated in an outer class, so if I need to set target layers, the target layers should be [self.base_vit.blocks[-1].norm1] rather than [self.blocks[-1].norm1]. But it seems that the pytorch hook will not be triggered if set target_layers=[self.base_vit.blocks[-1].norm1]. Did anyone encounter such issue?

**Comment by jacobgil** [comment]
Will need more details and a code snippet to try help.
How is base_vit defined ? etc.
Closing, please re-open if you can share more details.
