### ISSUE TITLE
any methods to aggregate the individual face heat maps?

### ISSUE THREAD

**Issue by qianqiancui** [jacobgil/pytorch-grad-cam#219]
Hi there!

Thanks for bringing us such a great project. I plan to get an aggregated heat map for a set of faces and wonder if there are methods to do that? Would it be possible to take the data underlying the heatmap, for each image, get the average intensity for each pixel across a set of images, and then feed the averages into the heat map generator? 

Thanks!

**Comment by jacobgil** [comment]
Hi,
Can you please share more details.
Are the faces aligned ? Are they of the same or of different people?
The heatmap itself would take the shape of the face, and would be like an ellipse i guess.
What do you want to achieve by aggregating the heatmaps, seeing the "typical" shape?
Do you want to aggregate the heatmaps (e.g with the saliency values per pixel), or the actual face pictures?

**Comment by qianqiancui** [comment]
Hi there!

Thanks so much for getting back to me. Yes, the faces are from different people but they are aligned. 
I'm comparing two models and wondering if one of them can make biased judgements on the set of faces (for example, check if they fail to detect some features in the face). 
Ideally, generate an aggregated heatmap on the same set of image for both models, so that we can determine whether the biased judgement is just on one or two  faces versus the entire face set.
And yes, it would be great if I can just aggregate the heatmaps (or get saliency values per pixel). Not the actual face pictures since I don't plan to include them in this type of analysis
Sorry for the long response and I understand that you are super busy. Thanks in advance for your time and please let me know if there's info I can provide. Appreciate your time!

**Comment by jacobgil** [comment]
If they are aligned, I would start by just taking the heatmaps per face (grayscale_cam in the examples), 
and taking the minimum value among all of them, to see where there are "misses".
so if aggregated_faces has the shape 50 x 256 x 256, for example for 50 faces,
```python
np.minimim(aggregated_faces, axis=0).
```
Then maybe the average.
You can also take the SVD across all of the heatmaps to create the "typical" heatmap:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/utils/svd_on_activations.py#L4

The face features from CAM will be more "wide" usually I guess, and might not necessarily give you an idea about the attention in lower level features like the nose or ears, for example. 
So you might also want to try earlier layers from the network in target_layer.
