### ISSUE TITLE
GradCAM results doesn't seem valid with resenet50

### ISSUE THREAD

**Issue by zeeshanahmad10809** [jacobgil/pytorch-grad-cam#224]
`
import cv2
import torch
import numpy as np
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image, preprocess_image
from torchvision.models import resnet50
from torchvision import transforms
import matplotlib.pyplot as plt

rgb_img = cv2.imread("/home/zeeshan/Downloads/dog.jpg")
rgb_img = np.float32(rgb_img) / 255
input_tensor = preprocess_image(rgb_img,
                                mean=[0.485, 0.456, 0.406],
                                std=[0.229, 0.224, 0.225])

model = resnet50(pretrained=True)
target_layers = [model.layer4]
cam = GradCAM(model=model, target_layers=target_layers)

grayscale_cam = cam(input_tensor=input_tensor, targets=None)

grayscale_cam = grayscale_cam[0, :]
visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)
visualization = cv2.cvtColor(visualization, cv2.COLOR_BGR2RGB)

plt.imshow(visualization)
`

I am not getting the desired result? Could somebody please help me out, here is the [link](https://www.pexels.com/photo/short-coated-tan-dog-2253275/) to the image.

**Output Generated**
![Current Output](https://user-images.githubusercontent.com/61353048/161744206-94c822f3-69a8-4680-adbf-78c4776dbd23.jpg)

**Desired Output**
![index](https://user-images.githubusercontent.com/61353048/161744508-5c264ffb-1f70-46de-92d5-d8eaf793e84e.png)

**Comment by jacobgil** [comment]
Can you please:
- Paste the original here, so I can take a look.
- Retry, but when resizing the image to 224x224, so it's in the scale the model expectes. To rule out it's because the model can't recognize dogs that are so large.

**Comment by zeeshanahmad10809** [comment]
Thank you so much. The problem was resolved when I resized it to 224x224.
