### ISSUE TITLE
How to use Grad-cam in my own trained VIT model?

### ISSUE THREAD

**Issue by SunJJ1996** [jacobgil/pytorch-grad-cam#229]
I can get the output when using 
`    model = torch.hub.load('facebookresearch/deit:main',
                           'deit_tiny_patch16_224', pretrained=True)`

Then, I trained **deit** using [https://github.com/facebookresearch/deit](url) in my own classification dataset. The checkpoint is in this location : "Output/best_checkpoint.pth"

So how can I load this model and obtain the grad-cam result?
Thank you if you can give me the answer.

**Comment by jacobgil** [comment]
Hi,
Please follow the example here:
https://github.com/jacobgil/pytorch-grad-cam/tree/master/usage_examples

And re-open in case there are more questions.
