### ISSUE TITLE
 Cam_gb.jpg's result is very bad.

### ISSUE THREAD

**Issue by Rmuli** [jacobgil/pytorch-grad-cam#23]
**cam_gb.jpg**'s result is very bad. Can I ask you whether the result of your program is the same? But **cam_gb.jpg** works well in **keras**(https://github.com/jacobgil/keras-grad-cam). What's the solution?

cam.jpg
![c-grad_cam](https://user-images.githubusercontent.com/37521721/62263864-3c167980-b450-11e9-9163-09bd7e39ba3d.jpg)

gb.jpg
![c-gb](https://user-images.githubusercontent.com/37521721/62263866-3e78d380-b450-11e9-81d9-6c039cc37976.jpg)

cam_gb.jpg
![1](https://user-images.githubusercontent.com/37521721/62263855-2e60f400-b450-11e9-93ae-7d756dad43a9.png)

**Comment by Terahezi** [comment]
same problem

**Comment by jacobgil** [comment]
Fixed.
