### ISSUE TITLE
Notebook tutorial for YOLO5 not working

### ISSUE THREAD

**Issue by ScantyDaemon** [jacobgil/pytorch-grad-cam#234]
![132131232131312](https://user-images.githubusercontent.com/26326194/163568411-63e15d1c-6c96-4bbd-a1a2-d40e7fcd723a.PNG)

**Comment by jacobgil** [comment]
Hello,
I couldn't reproduce this.
Are you using the package as installed with pip, or source code from github?
If from pip, can you please install the latest version ?
A bug that could be related to this was fixed in the recent version, that's why I'm thinking about this.

**Comment by ScantyDaemon** [comment]
Hello, I added the installation of the latest version of the grad cam library from git, but I began to give a different error.

![21323123123](https://user-images.githubusercontent.com/26326194/163681054-8e563dcd-8d63-420e-ba03-c3f8d106e6ac.PNG)

I really want to understand what I'm doing wrong and learn how to avoid such problems with new libraries for me, I beg you, help me figure it out, I'm attaching a [link](https://colab.research.google.com/drive/1pL7Ud6zuylStinJAy5RARRIvswq6czQA?usp=sharing) with my example code

**Comment by ScantyDaemon** [comment]
I apologize for the trouble, most likely the problem was in the Google Collab service, when I launched it on my desktop, everything worked right away.
![1232132313123](https://user-images.githubusercontent.com/26326194/163681699-0d98f26b-4e8e-41bc-8e0a-6286594bac06.PNG)
