### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by xiaoma-ux** [jacobgil/pytorch-grad-cam#239]
![image](https://user-images.githubusercontent.com/69418545/165083677-edc85ba5-2c3a-4068-8e00-a7624b305573.png)

**Comment by jacobgil** [comment]
Hi,
I'm sorry, can't help here with out details like:
- Which model, what are the input and the outputs
- What are the target layers, and the targets.

If you can share this please re-open.
