### ISSUE TITLE
Explaining  'ConvNeXt' models

### ISSUE THREAD

**Issue by jaiswati** [jacobgil/pytorch-grad-cam#240]
Hello @jacobgil,

Need your help to understand, what changes are required to explain  'ConvNeXt' models using current pytorch-based explanation methods.

Waiting for the response.

   Best,
@jaiswati

**Comment by jacobgil** [comment]
Closing this for now, not familiar enough with ConvNeXt, although it seems this should be supported out of the box.
If you can please clarify what did you try and what didn't work I can try helping.
