### ISSUE TITLE
ScoreCAM seems to be dependent on target_layers

### ISSUE THREAD

**Issue by ShaileshSridhar2403** [jacobgil/pytorch-grad-cam#243]
Hi,
ScoreCAM is meant to be independent of target_layers, as evidenced by the message:
` "Warning: You are using ScoreCAM with target layers, however ScoreCAM will ignore them."`. 
However, passing in an empty list as `target_layers` throws the following error:
```
/content/pytorch-grad-cam/pytorch_grad_cam/base_cam.py in aggregate_multi_layers(self, cam_per_target_layer)
    136 
    137     def aggregate_multi_layers(self, cam_per_target_layer: np.ndarray) -> np.ndarray:
--> 138         cam_per_target_layer = np.concatenate(cam_per_target_layer, axis=1)
    139         cam_per_target_layer = np.maximum(cam_per_target_layer, 0)
    140         result = np.mean(cam_per_target_layer, axis=1)

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate
```
Upon further examination of the source code, ([lines 11-13](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/activations_and_gradients.py#:~:text=for%20target_layer%20in,register_forward_hook(self.save_activation))) in activations_and_gradients.py seem to be registering hooks and saving activations only for the specified target_layers.

Finally, the output of the vit_explain code indeed varies based on the value of target_layers passed(I'm using vit_base_patch32_224 from timm as the model):

`target_layers = [model.blocks[-1].norm1]`
![scorecam_1](https://user-images.githubusercontent.com/29563101/166231679-61f33023-33ff-4bec-9095-4d194be5bef6.png)

`target_layers = [model.blocks[-2].norm1]`
![scorecam_2](https://user-images.githubusercontent.com/29563101/166231896-8bafb9c7-3343-4c0b-b023-86ebde9bbe9e.png)

Am I missing something?
Thanks!

**Comment by flymin** [comment]
@ShaileshSridhar2403 Hi, I also notice this mismatch. From my understanding, scorecam actually can be used for any target layers, because it just changes the weight of the activation map as gradcam. Do you have any idea?

**Comment by ShaileshSridhar2403** [comment]
Hey @flymin yeah, scorecam is definitely dependent on the target layers passed. I think the Warning message should just be ignored :). @jacobgil Do you have any comments?

**Comment by jacobgil** [comment]
You are 100% right.
I removed the warning in the repository, will update in pypi soon.
