### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'target_category'

### ISSUE THREAD

**Issue by xiaoguoguo2018** [jacobgil/pytorch-grad-cam#244]
I installed it using the command pip install grade-cam results.

But when I use the cam.py file provided in the project, note that I did not make any changes, I get the error "TypeError: __call__() got an unexpected keyword argument 'target_category' ".
I think this is an error inside the project, when I comment out this line, the program runs successfully, but how can I solve this problem?

![image](https://user-images.githubusercontent.com/40911688/166476950-019336fe-083c-4c91-a210-568aded709d3.png)

Thank you for your help!

**Comment by jacobgil** [comment]
Hi, it should be "targets" which is a list with the target per batch, or None.
Please see the Readme or cam.py.
