### ISSUE TITLE
Hello author, I am having some problems using my Semantic segmentation network to get the class activation map .When I apply cam to my Semantic segmentation network，it has an error：An exception occurred in CAM with block: <class 'IndexError'>. Message: index 1 is out of bounds for dimension 0 with size 1,NameError: name 'cam_image' is not defined,I hope you can help me check the problem if you have time. Thank you very much

### ISSUE THREAD

**Issue by hellolly** [jacobgil/pytorch-grad-cam#246]
When I apply cam to my Semantic segmentation network，it has an error：An exception occurred in CAM with block: <class 'IndexError'>. Message: index 1 is out of bounds for dimension 0 with size 1,NameError: name 'cam_image' is not defined,I hope you can help me check the problem if you have time. Thank you very much

**Comment by hellolly** [comment]
Here's the code I'm running

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('ignore')
from torchvision.models.segmentation import deeplabv3_resnet50
import torch
import torch.functional as F
import numpy as np
import requests
import torchvision
from PIL import Image
from pytorch_grad_cam.utils.image import show_cam_on_image, preprocess_image
import cv2
import json
from model import RCAN
import argparse
from torchvision import transforms

parser = argparse.ArgumentParser()
parser.add_argument('--scale', type=int, default=4)
parser.add_argument('--num_features', type=int, default=64)
parser.add_argument('--num_rg', type=int, default=10)
parser.add_argument('--num_rcab', type=int, default=20)
parser.add_argument('--reduction', type=int, default=16)
opt = parser.parse_args()

pallette_path = "./palette.json"
with open(pallette_path, "rb") as f:
    pallette_dict = json.load(f)
    pallette = []
    for v in pallette_dict.values():
        pallette += v

image_path = "image_results/000001.png"
# image = Image.open(image_path)
image = np.array(Image.open(image_path))
rgb_img = np.float32(image) / 255
input_tensor = transforms.ToTensor()(image).unsqueeze(0)
model = RCAN(opt)
model.load_state_dict(torch.load("weights/RCAN_epoch_100_tailseg_unme_a=0.001"))
model = model.eval()


if torch.cuda.is_available():
    model = model.cuda()
    input_tensor = input_tensor.cuda()

_,output = model(input_tensor)
prediction = output.argmax(1).squeeze(0)
prediction = prediction.to("cpu").numpy().astype(np.uint8)
mask = Image.fromarray(prediction)
mask.putpalette(pallette)
mask.save("image_results/000001_seg.png")

normalized_masks = torch.nn.functional.softmax(output, dim=1).cpu()

sem_classes = [
    '__background__', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus',
    'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike',
    'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor'
]
sem_class_to_idx = {cls: idx for (idx, cls) in enumerate(sem_classes)}

car_category = sem_class_to_idx["person"]
car_mask = normalized_masks[0, :, :, :].argmax(axis=0).detach().cpu().numpy()
print(car_mask.shape)
car_mask_uint8 = 255 * np.uint8(car_mask == car_category)
car_mask_float = np.float32(car_mask == car_category)



from pytorch_grad_cam import GradCAM


class SemanticSegmentationTarget:
    def __init__(self, category, mask):
        self.category = category
        self.mask = torch.from_numpy(mask)
        if torch.cuda.is_available():
            self.mask = self.mask.cuda()

    def __call__(self, model_output):
        return (model_output[self.category, :, :] * self.mask).sum()


target_layers = [model.seg.backbone.layer4]

targets = [SemanticSegmentationTarget(car_category, car_mask_float)]

with GradCAM(model=model,
             target_layers=target_layers,
             use_cuda=torch.cuda.is_available()) as cam:
    print("hahaha")
    grayscale_cam = cam(input_tensor=input_tensor,
                        targets=targets)[0, :]
    cam_image = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

    grayscale_cam = grayscale_cam*255

cam_image = cv2.cvtColor(cam_image, cv2.COLOR_RGB2BGR)
cv2.imwrite("image_results/seg_person.png",cam_image)
cv2.imwrite("image_results/seg_gray_person.png",grayscale_cam)
Image.fromarray(cam_image)

**Comment by hellolly** [comment]
#Here is the structure of my segmentation network

import torchvision.models.segmentation
from torch import nn
import torch



class ChannelAttention(nn.Module):
    def __init__(self, num_features, reduction):
        super(ChannelAttention, self).__init__()
        self.module = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(num_features, num_features // reduction, kernel_size=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(num_features // reduction, num_features, kernel_size=1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return x * self.module(x)


class RCAB(nn.Module):
    def __init__(self, num_features, reduction):
        super(RCAB, self).__init__()
        self.module = nn.Sequential(
            nn.Conv2d(num_features, num_features, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(num_features, num_features, kernel_size=3, padding=1),
            ChannelAttention(num_features, reduction)
        )

    def forward(self, x):
        return x + self.module(x)


class RG(nn.Module):
    def __init__(self, num_features, num_rcab, reduction):
        super(RG, self).__init__()
        self.module = [RCAB(num_features, reduction) for _ in range(num_rcab)]
        self.module.append(nn.Conv2d(num_features, num_features, kernel_size=3, padding=1))
        self.module = nn.Sequential(*self.module)

    def forward(self, x):
        return x + self.module(x)


class RCAN(nn.Module):
    def __init__(self, args):
        super(RCAN, self).__init__()
        scale = args.scale
        num_features = args.num_features
        num_rg = args.num_rg
        num_rcab = args.num_rcab
        reduction = args.reduction

        self.sf = nn.Conv2d(3, num_features, kernel_size=3, padding=1)
        self.rgs = nn.Sequential(*[RG(num_features, num_rcab, reduction) for _ in range(num_rg)])
        self.conv1 = nn.Conv2d(num_features, num_features, kernel_size=3, padding=1)
        self.upscale = nn.Sequential(
            nn.Conv2d(num_features, num_features * (scale ** 2), kernel_size=3, padding=1),
            nn.PixelShuffle(scale)
        )
        #self.sr_rcan = nn.Sequential(*[RG(64,10,16) for _ in range(5)])
        self.sr = nn.Conv2d(num_features, 3, kernel_size=3, padding=1)
        #self.seg = nn.Sequential(nn.Conv2d(num_features,num_features,kernel_size=3,padding=1),
                                  #nn.Conv2d(num_features,21,kernel_size=3,padding=1),
                                 #)
        self.segpro = nn.Conv2d(64,3,kernel_size=3,padding=1)
        self.seg = torchvision.models.segmentation.deeplabv3_resnet50(pretrained=True)
        #self.seg = network.deeplabv3_mobilenet()


    def forward(self, x):
        x = self.sf(x)
        residual = x
        x = self.rgs(x)
        x = self.conv1(x)
        x += residual

        x = self.upscale(x)
        seg = self.segpro(x)
        seg = self.seg(seg)['out']
        #seg = self.seg(seg)
        sr = self.sr(x)

        
        return sr,seg

**Comment by jacobgil** [comment]
Does the segmentation model have one output, or two outputs ?
I see it returns sr,seg and just seg, but wasn't sure this was the model.

**Comment by wutiaojian8** [comment]
I met the same issue. The reason seems to be the grad from target_layer is None, and it cannot be calculated.
I don't know how to solve it next.

**Comment by Julywuuu** [comment]
I

> I had the same issue. The reason seems to be that the grad from target_layer is None, and it cannot be calculated. I changed the code in basecam line 81 to` loss = targets[0](sum(outputs))`, the gradient reappears.

I had tried your method, it did't work in my codes. but i changed the code in basecam line82 to

**loss = sum( [ target(sum(output)) ] )**

it worked.
