### ISSUE TITLE
Implement Element-wise GradCam

### ISSUE THREAD

**Issue by maiskovich** [jacobgil/pytorch-grad-cam#247]
Hello, 

Thank you very much for your work, this package is great and makes many things easier.

I am trying to test an "Element-wise" implementation of GradCAM as is explained in this paper https://www.aaai.org/AAAI21Papers/AAAI-8236.PillaiV.pdf

As part of that publication, they shared this code: https://github.com/UMBCvision/Explainable-Models-with-Consistent-Interpretations/blob/main/utils.py#L103, which explains that GradCAM implementation but is quite specific to the model they built (they save the gradients as part of the forward pass of the model, as they explicitly defined that in the forward method)

I tried implementing a `get_cam_weights`, which will be element-wise, trying mimicking that behavior, this is what I got:
  ```
def get_cam_weights(self,
                      input_tensor,
                      target_layer,
                      target_category,
                      activations,
                      grads):
      eps = 1e-8
      gcam512_1 = grads * activations
      gradcam = gcam512_1.sum(axis=1)
      spatial_sum1 = gradcam.sum(axis=(1, 2))
      spatial_sum1 = np.expand_dims(spatial_sum1,axis=-1)
      spatial_sum1 = np.expand_dims(spatial_sum1, axis=-1)
      gradcam = (gradcam / (spatial_sum1 + eps)) + eps
      return gradcam```


And I ended up needing to comment on the line that does the elementwise multiplication between weights and activations already built in this package:
`weighted_activations = weights[:, :, None, None] * activations`
(line 55 in `base_cam.py`)

But my visualization results end up looking like they don't make any sense.


Could you please provide some guidance on how to approach this problem? I hope to make it work and I would like to contribute with a pull request if I have this functionality in place

**Comment by jacobgil** [comment]
Hi, thanks.


Yeah I guess this part of how to implement new methods isn't really documented. I thought it's too much for the Readme. Maybe it's time for a website..

To implement new methods, there are two methods to consider.
- `get_cam_weights` - This is useful when the final CAM is along the lines of sum (scalar_weights * spatial_activations).
This computes a weight per channel. For example in grad-cam.

- `get_cam_image` - This is useful when it doesn't fall in this pattern, and you want to compute the CAM in another way.
For example in the element-wise method you shared above, they don't have a single weight per channel but it's done in another way. So you can just use this function to compute the CAM directly.

In the layer-cam method, the implementation is almost identical to elementwise-cam:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/layer_cam.py#L30
The only difference is that the ReLu operator should be moved to be outside of the multiplication, so `spatial_weighted_activations = np.maximum(grads * activations, 0)`.
So you can use layer-cam as a reference for elementwise-cam.

It's funny, at some point all of the combinations of grads and activations with ReLU are tried.

Hope this helps.

**Comment by maiskovich** [comment]
Thank you very much!

I will try to implement based on layer-cam.

Yes, each paper claims that their specific way of doing cam is the right way, need to test it...

**Comment by jacobgil** [comment]
Great.
I'm closing this issue, please re-open it if you have any questions.
