### ISSUE TITLE
AxisError: axis 3 is out of bounds for array of dimension 3

### ISSUE THREAD

**Issue by hbrachemi** [jacobgil/pytorch-grad-cam#248]
Hey, 
I am trying to compute the grad cam on the TimeSformer architecture, The model takes an input of dimensions (batch_size, channels, number of frames,224,224) and couldn't figure out what's causing this issue.

![image](https://user-images.githubusercontent.com/68550699/168272520-654436e8-3433-4def-84cf-895af0156d46.png)

![image](https://user-images.githubusercontent.com/68550699/168272122-32e86790-7f0c-4c5d-94d5-6f24268c1332.png)

**Comment by jacobgil** [comment]
Hi,
Until now the input sizes are always those of a single image: channels x height x width.

I think it should be possible to adapt this for the case of a time series, but it's not supported yet out of the box.

Is there a chance you can share details,
is there some code snippet that could be used to test this on TimeSformer  ?

**Comment by hbrachemi** [comment]
Sorry for the late reply;
Their code is available on https://github.com/facebookresearch/TimeSformer
However, I still face a problem when running the code on a regular vision transformer which I think is due to me using the model for a regression task rather than a classification.
![image](https://user-images.githubusercontent.com/68550699/168447396-333940e8-5c47-49dd-8901-d8b0be5b0dab.png)
I could share as well the code I used if it helps reproduce the error

**Comment by hbrachemi** [comment]
Update:
I figured out the exception was generated due to a matrix multiplication of the last layer with the model's output, which was a scaler in my case.
Thanks again and sorry for the inconvenience
