### ISSUE TITLE
Average Pool Layer

### ISSUE THREAD

**Issue by AsimJalwana** [jacobgil/pytorch-grad-cam#25]
Hi, 

I was going through the implementation, I found that the 'avgpool' layer is ignored. In the Class "ModelOutputs", in __call__(), the output from FeatureExtractor is simply passed to the classification part of the network, ignoring the "avgPool" altogether. 

Can you please guide me what am I missing?

Regards,
Asim

**Comment by gistest1** [comment]
Because only the basenet part ('model.features' to vgg) was initialized in FeatureExtractor. 
line 39: self.feature_extractor = FeatureExtractor(self.model.features, target_layers)

**Comment by AsimJalwana** [comment]
You are right about the use of 'features part' in Line 39. But the forward pass of vgg19 (taken from the Pytorch lib is shown below)

![image](https://user-images.githubusercontent.com/40447398/70584023-8a0b6d00-1bfa-11ea-9335-96eb377cb6c3.png)


They explicitly use the avgPooling in the forward pass. The backward pass will, however, include the avgPool layer since it is the part of the network. Since were are computing layer by layer activations, so I guess it got simply missed and it should have been there. 

Do you agree?

**Comment by gistest1** [comment]
Sorry for misunderstanding your question. I simply applied this implementation to my own model, and didn't go through the details of the forward process. 
But I think you are right. In this implementation, the output of the FeatureExtractor is simply passed to the fc-classifier and ignored the avgpool layer.

**Comment by AsimJalwana** [comment]
Thank you for replying, you are right, the avgpool layer just got ignore.
