### ISSUE TITLE
Visualization with multiple inputs in forward method

### ISSUE THREAD

**Issue by jofragotre** [jacobgil/pytorch-grad-cam#253]
Hello, I have a network for which the forward method is defined with two inputs e.g: `pred = model(image1, image2)`.
As for now I haven't been able to use grad-cam. I tried defining `input_tensor = (image1, image2)` but with no sucess. Is there anyway use grad-cam for such network (from my understanding in theory should be possible). 
Thanks in advance! :)

**Comment by jacobgil** [comment]
Hi,
I think this could be done by creating a custom reshape_transform,
but I need more details.
How does the model look ?
In the layer you want to target, are there spatial activations from both images?
