### ISSUE TITLE
problem visual Vit model

### ISSUE THREAD

**Issue by johnwalking** [jacobgil/pytorch-grad-cam#257]
hello authors,
I got a problem while trying to use grad cam in my ViT model,
it always get error "An exception occurred in CAM with block: <class 'numpy.AxisError'>. Message: axis 3 is out of bounds for array of dimension 3"
Could you help me?

**Comment by jacobgil** [comment]
Hello,
Did you use a reshape transform and follow the examples for ViT?
Can you share a code snippet ?

**Comment by johnwalking** [comment]
thanks for replying,
I did reshape the image.
here is what I add.
```
    target_layers = [model.blocks[-1].norm1]

    rgb_img = cv2.imread(args.image_path, 1)[:, :, ::-1]
    rgb_img = cv2.resize(rgb_img, (224, 224))
    rgb_img = np.float32(rgb_img) / 255
    input_tensor = preprocess_image(rgb_img,
                                    mean=[0.485, 0.456, 0.406],
                                    std=[0.229, 0.224, 0.225])

    print(input_tensor.size())
```

**Comment by jacobgil** [comment]
The internals of ViT are different (the activations have different shapes than in CNNs), so it needs some care.
Please follow the example hre:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/usage_examples/vit_example.py

Specifically you need to pass a reshape function that reshapes the tensors and discards the class token:
```python
def reshape_transform(tensor, height=14, width=14):
    result = tensor[:, 1:, :].reshape(tensor.size(0),
                                      height, width, tensor.size(2))

    # Bring the channels to the first dimension,
    # like in CNNs.
    result = result.transpose(2, 3).transpose(1, 2)
    return result
```

and then pass reshape_transform=reshape_transform when constructing the cam.

**Comment by johnwalking** [comment]
thanks a lot , it works!

**Comment by edmondja** [comment]
reshape_transform=reshape_transform is ignored, I had a shape problem, saying 14 by 14 did not match my input, I tried to switch to 12 by 12 by changing the default height and width with no success. Do you have a quickfix for this ?
