### ISSUE TITLE
Access layer from traced module (script with jit)

### ISSUE THREAD

**Issue by BaptisteAmato** [jacobgil/pytorch-grad-cam#258]
Hi,

I would like to use gradcam with a scripted module, i.e. after:
`model = torch.jit.load('my_weights.pt')`

Indeed, I need to use model.layer4[-1] which is not accessible with a torch script...

Thanks for your work,
Best

**Comment by jacobgil** [comment]
Will look into this, will probably take a few days.

**Comment by jacobgil** [comment]
Hi,
You can just do model.layer4 and it will work.

But there is another problem.
This repo makes use of forward and backward hooks, and torchscript doesn't support them unfortunately:
https://discuss.pytorch.org/t/register-forward-hook-is-not-supported-on-scriptmodules/57009/2

So until it does, I don't think it will work, unfortunately.

**Comment by BaptisteAmato** [comment]
Yes that's the problem :(
Alright, thanks anyway!
