### ISSUE TITLE
How to adapt this for densenet121?

### ISSUE THREAD

**Issue by gokriznastic** [jacobgil/pytorch-grad-cam#26]

**Comment by jiashenC** [comment]
I wonder the same. What about MobileNetV2?

**Comment by frgfm** [comment]
If you're still looking for a viable solution, this might help you: https://github.com/frgfm/torch-cam
There is an example script for easy comparison of all CAM methods and you can specify any classification model from torchvision (mobilenet included). You can use any model if you modify the template script a bit as well :ok_hand: 

Let me know if it helped!

**Comment by jacobgil** [comment]
Now supports DenseNet, just do
target_layer = model.features[-1]
