### ISSUE TITLE
Can I use it for 3D models ? And what is the parameter target for these segmentation models?

### ISSUE THREAD

**Issue by ReemShalaata** [jacobgil/pytorch-grad-cam#261]
I have a 3D Unet model  that takes as input a 5D tensor of size (1,1,4,256,256) which is 4 frame video and outputs a 5D tensor (1,3,4,256,256) a video predicted mask for 3 labels .

Can I use the library or its not suitable for my segmentation problem ,in case I can use it what's the target parameter supposed to be .

**Comment by PascalHbr** [comment]
I would also be interested in this!

**Comment by ReemShalaata** [comment]
> Hi,
> The target parameter can be the same for 2D.
> 
> I think there can be some size mismatches for 3D (I never tried it before yet).
> I plan to look into this in the next few days, will respond in this issue when I do.
> 

Thanks 
For now I switched to captum  and it worked for me

**Comment by dmoltisanti** [comment]
> > > > Hi,
> > > > The target parameter can be the same for 2D.
> > > > I think there can be some size mismatches for 3D (I never tried it before yet).
> > > > I plan to look into this in the next few days, will respond in this issue when I do.
> > > 
> > > 
> > > Thanks For now I switched to captum and it worked for me
> > 
> > 
> > Hi @ReemShalaata
> > would you have any pointers to how you managed to use Captum on 3D models? I need to compute gradcam visualisation for my 3D model (in my case, it's I3D) and it seems that unfortunately there aren't many libraries out there for 3D gradcam.
> > Thanks!
> 
> Hello @dmoltisanti I asked them here and the links they provided helped me [pytorch/captum#962](https://github.com/pytorch/captum/issues/962)
> 
> Hopefully it will help you Good luck

Thanks a lot, I'll have a look!

**Comment by zimengxueying** [comment]
> > > > > Hi,
> > > > > The target parameter can be the same for 2D.
> > > > > I think there can be some size mismatches for 3D (I never tried it before yet).
> > > > > I plan to look into this in the next few days, will respond in this issue when I do.
> > > > 
> > > > 
> > > > Thanks For now I switched to captum and it worked for me
> > > 
> > > 
> > > Hi @ReemShalaata
> > > would you have any pointers to how you managed to use Captum on 3D models? I need to compute gradcam visualisation for my 3D model (in my case, it's I3D) and it seems that unfortunately there aren't many libraries out there for 3D gradcam.
> > > Thanks!
> > 
> > 
> > Hello @dmoltisanti I asked them here and the links they provided helped me [pytorch/captum#962](https://github.com/pytorch/captum/issues/962)
> > Hopefully it will help you Good luck
> 
> Thanks a lot, I'll have a look!

Hi! I met the same problem ,have you ever solved? Thank you so much!

**Comment by dmoltisanti** [comment]
Hey there, sorry but eventually I gave up and used [spatio-temporal perturbations](https://github.com/shinkyo0513/Spatio-Temporal-Perturbations-for-Video-Attribution) instead. Good luck!

**Comment by zimengxueying** [comment]
> Hey there, sorry but eventually I gave up and used [spatio-temporal perturbations](https://github.com/shinkyo0513/Spatio-Temporal-Perturbations-for-Video-Attribution) instead. Good luck!

Thank you for your kindness!

**Comment by ReemShalaata** [comment]
> > > > > > Hi,
> > > > > > The target parameter can be the same for 2D.
> > > > > > I think there can be some size mismatches for 3D (I never tried it before yet).
> > > > > > I plan to look into this in the next few days, will respond in this issue when I do.
> > > > > 
> > > > > 
> > > > > Thanks For now I switched to captum and it worked for me
> > > > 
> > > > 
> > > > Hi @ReemShalaata
> > > > would you have any pointers to how you managed to use Captum on 3D models? I need to compute gradcam visualisation for my 3D model (in my case, it's I3D) and it seems that unfortunately there aren't many libraries out there for 3D gradcam.
> > > > Thanks!
> > > 
> > > 
> > > Hello @dmoltisanti I asked them here and the links they provided helped me [pytorch/captum#962](https://github.com/pytorch/captum/issues/962)
> > > Hopefully it will help you Good luck
> > 
> > Thanks a lot, I'll have a look!
> 
> Hi! I met the same problem ,have you ever solved? Thank you so much!

Hello 
You just need to choose the label each time you want to use captum library.
You should understand at end you can't draw for all the labels in one figure .
I will send the relevant code here soon .

**Comment by ReemShalaata** [comment]
@zimengxueying 

The mean thing you should understand is that when you will draw each time depends on the label you choose and the frame you choose .
Because it will draw it as a 2D image.

I will check out my code and explain more if needed .

**Comment by zimengxueying** [comment]
> 

Thank you for I'm the new about the visualization, thanks for your guide. The model I use is I3D, which is a 3D convolution for a series frames, so the input is (16,224,224,3) and 16 is the frames extracted from the video, and the output is (2048). So I just a bit confused how the 2048 applied in 16 frames because when it does the convolution it also computes the time dimension. Would you share the idea about it? Thank you so much!

**Comment by zimengxueying** [comment]
> @zimengxueying
> 
> The mean thing you should understand is that when you will draw each time depends on the label you choose and the frame you choose . Because it will draw it as a 2D image.
> 
> I will check out my code and explain more if needed .

Thank you for reply! I'm the new about the visualization, thanks for your guide. The model I use is I3D, which is a 3D convolution for a series frames, so the input is (16,224,224,3) and 16 is the frames extracted from the video, and the output is (2048). So I just a bit confused how the 2048 applied in 16 frames because when it does the convolution it also computes the time dimension. Would you share the idea about it? Thank you so much!

**Comment by Mukil07** [comment]
@zimengxueying

 Im also working on using CAM maps on I3D with Video data. Have you solved your problem ?

 Thank you !
