### ISSUE TITLE
Which CAM Variant I should use for my Data/Task?

### ISSUE THREAD

**Issue by therealgherkhin** [jacobgil/pytorch-grad-cam#262]
Hi @jacobgil ,
is there any Paper or suggestion that is about which CAM Variant should be used for a specific task. I see the difference from the mathematical standpoint, but does this transfers into the application of each variant?
I'm currently writing my thesis about CAM and can't seem to find literature about this.

**Comment by jacobgil** [comment]
Some illustration of this would be a great addition to the documentation of this repository;)
