### ISSUE TITLE
How to get Pixel Activation Maps for Semantic Segmentation？

### ISSUE THREAD

**Issue by UCPRER** [jacobgil/pytorch-grad-cam#263]
Hi, I want to get a activation maps that looking at one of the pixels in a semantic-segmentation model.
So i modified the code in ./tutorials/Class Activation Maps for Semantic Segmentation.ipynb
```
class SemanticSegmentationTarget:
    def __init__(self, category, mask):
        self.category = category
        self.mask = torch.from_numpy(mask)

        if torch.cuda.is_available():
            self.mask = self.mask.cuda()
        
    def __call__(self, model_output):
        return (model_output[:, 165, 250]).sum()
```
But the result is not quite as expected, I chose the point in the center of the graph, the point with the expected larger gradient should be the bird in the graph, but the result is the opposite.I wonder if I changed the code wrong.
![image](https://user-images.githubusercontent.com/53432924/171869039-f80e982f-3533-47bc-a6fe-fac248e13e19.png)

![image](https://user-images.githubusercontent.com/53432924/171868039-087b2601-0318-493d-b7fa-ea5b73cc1eca.png)

**Comment by jacobgil** [comment]
Hi,
How many categories does the model output have?
I suspect that when you're doing 
model_output[:, 165, 250]).sum()
It is summing accross all categories.

Maybe change to
model_output[1, 165, 250]) ?
To get the output from the first category ?
