### ISSUE TITLE
You are using ScoreCAM with target layers, however ScoreCAM will ignore them is occured

### ISSUE THREAD

**Issue by chenxinhe1** [jacobgil/pytorch-grad-cam#269]
Thank you for your work, When i run swinT_example.py, Warning: You are using ScoreCAM with target layers, however ScoreCAM will ignore them is occured, what is  the meaning of it? looking forward to your reply!

**Comment by jacobgil** [comment]
Hi, this can be ignored.
I will remove the warning in the next version.
