### ISSUE TITLE
The color of the background

### ISSUE THREAD

**Issue by Dongjiuqing** [jacobgil/pytorch-grad-cam#270]
Thanks for your work. 
I use the code of [EigenCAM for YOLO5.ipynb]
I test one image by using your example. But the color of the feature map for the background is red. In your example, the background should be blue. 
the result looks as follows:
I want to know the reason
<img width="1726" alt="result" src="https://user-images.githubusercontent.com/43560407/174472309-170c2f89-59b0-49fa-a293-6de59f87ec96.png">

**Comment by Dongjiuqing** [comment]
Actually, I fix this issue by set the param‘use_rgb=True’ -> 'use_rgb=False'

cam_image = show_cam_on_image(img, grayscale_cam, use_rgb=False)

But I still have a question. Why the result didn't focus on the target. Generally speaking, the red area should cover the bounding-box area. But the color of the target area is the same as the background area. Is the model or the code causing the problem?
<img width="1715" alt="result" src="https://user-images.githubusercontent.com/43560407/174473754-7dbedec1-bfe8-418a-acb5-a4413b26069d.png">

**Comment by jacobgil** [comment]
Hi,
It looks like the dominant features here are from the the yellow-pepper, and this is what Eigen-CAM returns.
This is a drawback of EigenCAM since it returns only the first principle vector.

**Comment by ivsim01** [comment]
Hi, sorry for opening this issue again, and thanks for your work! I'm also working with YOLOv5, EigenCAM and a custom trained model.

I am dealing with a similar application as the yellow pepper shown above. The EigenCAM prior re-normalization shows as well stronger activated pixels outside the predicted bounding box than within, but its confident score still achieves more than 90%. I was wondering how can both situations occur in parallel? Is this a flaw of the EigenCAM algorithm and thus requires the re-normalization? For example on the prior-normalization yellow-pepper image, some pixels on the hand are highly activated, how could we explain that with respect to the target?

If you could me explain a little bit more, it would be great!

**Comment by ivsim01** [comment]
Hi, @jacobgil ! Thanks for your work! I'm also working with YOLOv5, EigenCAM and a custom trained model.

I am dealing with a similar application as the yellow pepper shown above. The EigenCAM prior re-normalization shows as well stronger activated pixels outside the predicted bounding box than within, but its confident score still achieves more than 90%. I was wondering how can both situations occur in parallel? Is this a flaw of the EigenCAM algorithm and thus requires the re-normalization? For example on the prior-normalization yellow-pepper image, some pixels on the hand are highly activated, how could we explain that with respect to the target?

If you could me explain a little bit more, it would be great!
