### ISSUE TITLE
Use this package on Huggingface vision transformers.

### ISSUE THREAD

**Issue by raedinkhaled** [jacobgil/pytorch-grad-cam#273]
### Discussed in https://github.com/jacobgil/pytorch-grad-cam/discussions/271

<div type='discussions-op-text'>

<sup>Originally posted by **raedinkhaled** June 19, 2022</sup>
Hello,

I fined tuned a ViT from Huggingface and pushed it to hub. How can I implement pytorch-grad-cam on the models from Huggingface ?</div>

**Comment by jacobgil** [comment]
https://jacobgil.github.io/pytorch-gradcam-book/HuggingFace.html
Here you go :-)
