### ISSUE TITLE
How can grad-cam be used in siamese  networks?

### ISSUE THREAD

**Issue by Yanll2021** [jacobgil/pytorch-grad-cam#277]
I'm sorry to bother you, but I would like to know that how can GRAD-CAM be used in siamese  networks with shared weights, such as change detection of remote sensing image, which contains two inputs., and they are feed into the siamese feature extraction network. I want to visualize the visual feature map of a certain layer of dual-phase input in feature extraction, respectively. How can I use your Grad-CAM?

**Comment by Bangbangbanana** [comment]
The paper [Visual Explanation for Deep Metric Learning](https://arxiv.org/abs/1909.12977) and its code [https://github.com/Jeff-Zilence/Explain_Metric_Learning](https://github.com/Jeff-Zilence/Explain_Metric_Learning) may help you.

**Comment by Yanll2021** [comment]
> 
Thank you very much for your reply. I will refer to it carefully.

**Comment by Yanll2021** [comment]
> The paper [Visual Explanation for Deep Metric Learning](https://arxiv.org/abs/1909.12977) and its code https://github.com/Jeff-Zilence/Explain_Metric_Learning may help you.
I'm sorry. I'm still in a bit of trouble.  My task is change detection based on siamese network, which is similar to semantic segmentation task but contains double input. I have referenced the method in the paper you recommended, but the effect is poor.  I think this may be due to the fact that my task is similar to semantic segmentation tasks, but I don't know how to modify them.  At present, my some visualization results of feature map of middle layer are as follows. If you have good suggestions, I am very grateful! 
![image](https://user-images.githubusercontent.com/78201260/175826114-85f3325d-050c-4e6e-b04b-fdcfbf6bbb21.png)
![image](https://user-images.githubusercontent.com/78201260/175826138-dcacdd3d-c6eb-4d49-817b-77fdce745e2f.png)

**Comment by jacobgil** [comment]
Thanks for sharing that paper, I wasn't aware of it.

We have a notebook for this case - explaining the similarly of images based on the embeddings - 
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Pixel%20Attribution%20for%20embeddings.ipynb

**Comment by IceHowe** [comment]
> > The paper [Visual Explanation for Deep Metric Learning](https://arxiv.org/abs/1909.12977) and its code https://github.com/Jeff-Zilence/Explain_Metric_Learning may help you.
> > I'm sorry. I'm still in a bit of trouble.  My task is change detection based on siamese network, which is similar to semantic segmentation task but contains double input. I have referenced the method in the paper you recommended, but the effect is poor.  I think this may be due to the fact that my task is similar to semantic segmentation tasks, but I don't know how to modify them.  At present, my some visualization results of feature map of middle layer are as follows. If you have good suggestions, I am very grateful!
> > ![image](https://user-images.githubusercontent.com/78201260/175826114-85f3325d-050c-4e6e-b04b-fdcfbf6bbb21.png)
> > ![image](https://user-images.githubusercontent.com/78201260/175826138-dcacdd3d-c6eb-4d49-817b-77fdce745e2f.png)


Hello, do you solve this problem? I also need to visualize the heat map of the twin network

**Comment by Yzwfff** [comment]
> > The paper [Visual Explanation for Deep Metric Learning](https://arxiv.org/abs/1909.12977) and its code https://github.com/Jeff-Zilence/Explain_Metric_Learning may help you.
> > I'm sorry. I'm still in a bit of trouble.  My task is change detection based on siamese network, which is similar to semantic segmentation task but contains double input. I have referenced the method in the paper you recommended, but the effect is poor.  I think this may be due to the fact that my task is similar to semantic segmentation tasks, but I don't know how to modify them.  At present, my some visualization results of feature map of middle layer are as follows. If you have good suggestions, I am very grateful!
> > ![image](https://user-images.githubusercontent.com/78201260/175826114-85f3325d-050c-4e6e-b04b-fdcfbf6bbb21.png)
> > ![image](https://user-images.githubusercontent.com/78201260/175826138-dcacdd3d-c6eb-4d49-817b-77fdce745e2f.png)

您好，这个问题你解决了吗，我也遇到和你一样的问题
