### ISSUE TITLE
How to apply Grad-CAM on YOLOv5?

### ISSUE THREAD

**Issue by Jonathan-CHJ** [jacobgil/pytorch-grad-cam#287]
Hi, 

I am quite new to XAI. Is it possible to apply Grad-CAM instead of EigenCAM on YOLOv5? I have faced an error when I am trying to use Grad-CAM on YOLOv5.

This is the code:
![image](https://user-images.githubusercontent.com/56185702/178129298-e7ca7880-8dcb-449d-8b76-c8af58542057.png)

This is the error:
![image](https://user-images.githubusercontent.com/56185702/178129304-3be81f26-aec3-4c41-adce-d486e94586d7.png)

**Comment by jacobgil** [comment]
Hi,
Grad-CAM isn't supported for YOLO5 because the gradient computation isn't exposed there.
Fortunately we can use gradient free methods, and have a tutorial exactly about this for YOLO5:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/EigenCAM%20for%20YOLO5.ipynb
