### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_grad_cam.utils.model_targets'

### ISSUE THREAD

**Issue by masterj7874** [jacobgil/pytorch-grad-cam#288]
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget

any idea?

**Comment by jacobgil** [comment]
Hi,
Did you install with pip install ?
Is it the latest version (if not, can you upgrade with --upgrade) ?

**Comment by masterj7874** [comment]
Thank you for the suggestion but it still produces the error. I've check the all python files and it's clearly there. And it works on Colab^^ but not on jupyter after pip installation. Maybe isomethin in my conda environment is not compatible withe grad-cam. I don;t know.

**Comment by jacobgil** [comment]
>>> import pytorch_grad_cam
>>> pytorch_grad_cam.__path__

Does that return what you expected ?

**Comment by masterj7874** [comment]
I rewrote the codes after tweaking jupyter notebook. and it works! Yes, pytorch_grad_cam.path returns where it is supposed to be. Thank you!
