### ISSUE TITLE
How can I implement Grad-CAM in object detection model??

### ISSUE THREAD

**Issue by SHAOSIHAN** [jacobgil/pytorch-grad-cam#30]
I find all code about Grad-CAM on github to be aimed classification model, so how can I implement Grad_CAM on object detection model that has two tasks: classification and regression??

**Comment by daiwc** [comment]
have you sucessfully apply GradCam on detection?

**Comment by SHAOSIHAN** [comment]
> have you sucessfully apply GradCam on detection?

Hello，I find a Grad-CAM project that can apply it on detection

Link:  https://github.com/yizt/Grad-CAM.pytorch
Maybe it can help you !

**Comment by withtimesgo1115** [comment]
Thank you very much!!! Nice share@SHAOSIHAN

**Comment by withtimesgo1115** [comment]
> > have you sucessfully apply GradCam on detection?
> 
> Hello，I find a Grad-CAM project that can apply it on detection
> 
> Link: https://github.com/yizt/Grad-CAM.pytorch
> Maybe it can help you !

Thank you very much!!! Nice share@SHAOSIHAN

**Comment by jacobgil** [comment]
Hi,
I'm happy to share that now there is a detailed notebook about how to use CAMs for object detection:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.ipynb
