### ISSUE TITLE
Can I apply this to depth estimation?

### ISSUE THREAD

**Issue by sjg02122** [jacobgil/pytorch-grad-cam#301]
Hello! Thank you for your great work. 

I was very impressed by your use of grad-cam for semantic segmentation.

Is it possible to apply to the depth estimation, which is pixel-wise prediction without class?

**Comment by jacobgil** [comment]
Yes.
So is the network doing regression of the depth basically ?

You can just use this target:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/utils/model_targets.py#L21

Pass category=1 if you want to visualize what causes a larger depth, and category = 0 if you want to visualize what causes a smaller depth.
