### ISSUE TITLE
Message: axis 2 is out of bounds for array of dimension 2

### ISSUE THREAD

**Issue by imran-suny** [jacobgil/pytorch-grad-cam#306]
![image](https://user-images.githubusercontent.com/61520633/182438797-5a5bf52b-086e-4044-a549-b6e0b289b2c8.png)

**Comment by jacobgil** [comment]
Flatten-514 won't work as a target layer. It has to be the 2D output of a CNN.
So Block8-511 for example or earlier, before the adaptive pooling that turns it into 1d
