### ISSUE TITLE
if I need grad-cam for just one class in image for instance only person how to specify one class?

### ISSUE THREAD

**Issue by noreenanwar** [jacobgil/pytorch-grad-cam#319]
Thank you so much for your work.I want tot ask that if I need grad-cam for just one class in image for instance only person how to specify one class?

**Comment by noreenanwar** [comment]
Can I combine two grad-cam from different images ?

**Comment by jacobgil** [comment]
Re the first image, what do you mean?
Does the network have one output with a sigmoid (predicting two categories), or what exactly ?

**Comment by noreenanwar** [comment]
> Re the first question, what do you mean?
> Does the network have one output with a sigmoid (predicting two categories), or what exactly ?

For Q1:it means if my image have bus , person ,benches but I will just get CAM for only one person.
For Q2: when I get CAM of a person from two images with same background can I combine there CAM?

**Comment by jacobgil** [comment]
The CAM methods work with a target.
Here is an example target from the README:
`targets = [ClassifierOutputTarget(281)]`

Here 281 is the category of a cat in imagenet.

You can just specify the category you're interested in, like the person, and pass it to the method.

Is this what you mean ?

**Comment by noreenanwar** [comment]
Ok thank you so much .I got it.
N what about combing two CAM?

**Comment by jacobgil** [comment]
Every CAM generated is for a specific image.
Can you clarify what combining two CAMs would mean?

**Comment by noreenanwar** [comment]
> Every CAM generated is for a specific image.
> Can you clarify what combining two CAMs would mean?

I meant to say that img1 have 2 persons (frame of  a video) and in img2 there are 3 persons (as it is from the  same video),can I combine CAM of img1 with img2? and give one output?
