### ISSUE TITLE
Grad-CAM for object detection (RetinaNet)

### ISSUE THREAD

**Issue by QuentinAndre11** [jacobgil/pytorch-grad-cam#326]
Hi! In your README, you explain that gradient based methods cannot be used on object detection problems (like for mine, object detection with RetinaNet), but I found this https://github.com/alexriedel1/detectron2-GradCAM. Is it, as you said, a specific method to solve the linearity problems which has been implemented and makes it work? 
I also have another question: what happens if I don't have any instance output by the model with my confidence threshold? No output images? Should I use at least one instance, the one with the best score, to know what happens in my network?
Thanks a lot for your work!

**Comment by jacobgil** [comment]
Hi,

- It's not that they can't be used, it's just that not all object detection frameworks expose the ability to compute gradients.
When that's the case, it's more convenient to use a gradient free method.

- Interesting question. I would say that yes, use the best score. Just like when applying these methods on classification models, not always the category gets a very confident score.
