### ISSUE TITLE
No attribution for past the first image in multi-label classification

### ISSUE THREAD

**Issue by dimasquest** [jacobgil/pytorch-grad-cam#328]
Hi,

I am running the basic version of GradCam on ResNet50 and DenseNet (although I verified this on other versions such as HighResCam etc.). 

I create a separate cam for each output class (14 in total) and record attributions per each specific label. When running the following code, the attribution is only created for the 1st image in the batch and the rest is ignored.

`grayscale_cams = [cam(input_tensor=selected_images, targets=[ClassifierOutputTarget(i)]) for i in range(num_classes)]`

`images, visualisations = denorm_images(selected_images, grayscale_cams, mean, std) `

   ```
 def denorm_images(image_batch, grayscale_cams, mean, std):

    .....

    # images - entire batch; grayscale_cam - GCams of a single class per each image

    visualization = show_cam_on_image(image, grayscale_cams[i], use_rgb=True)

    # convert into a plt-compatible format

    visualizations.append(torch.from_numpy(visualization.astype(np.float32) / 255.).permute(2, 0, 1))

     .....
```

However, replacing the first line with 
`grayscale_cams = [cam(input_tensor=selected_images, targets=None) for i in range(num_classes)]`
Always works as intended. The issue is that I need a separate attribution per each label (and setting target to None only does the most probable label). Moreover, when going over all 14 labels, at least one of them has to be the 'most probable one', but looking at the visualisations, this does not seem to be the case and only the first image gets the attribution. 

So the issue arises in the targets field, but I am not sure what can be the underlying cause of this behavior, could you potentially suggest what I need to look into?
This is the result of  targets=[ClassifierOutputTarget(i)]
![image](https://user-images.githubusercontent.com/25184323/188870042-cf175e47-742e-45e9-8913-9859557c8477.png)

This is the result of  targets=None
![image](https://user-images.githubusercontent.com/25184323/188870235-6e92a746-2b94-4329-9574-5849b4d49873.png)

**Comment by jacobgil** [comment]
Hi, sorry for the late reply.

I need some clarifications -
It looks like you have 32 images, and 14 categories.

What exactly do you want to do - create 14 different visualizations for each of the 32 images ?
In that case we will have 32*14 outputs.

I think it looks like currently there were 14 different visualizations for 32 images, but the image_i isn't necessarily explained well by category_i, and it's only for the first 14 images anyway.

**Comment by dimasquest** [comment]
Hi, 
So the idea is to get a separate grad_cam per each individual class (14 in total). And do this for each image in a batch (of which there are 32). 32x14 is indeed the size I am aiming for 

So (and please correct me if this is not what is happening in the code): for each cam (which corresponds to classes 0-13) I iterate over each image and get an attribution wrt this specific cam. I then make a grid out of them and save them. 

And this does not seem to work when I am assigning the individual classes to each cam through 
`[cam(input_tensor=selected_images, targets=[ClassifierOutputTarget(i)]) for i in range(num_classes)]`

As per image, this only attributes the first image and nothing else.

But replacing the targets=[ClassifierOutputTarget(i)]) with targets=None suddenly returns the attributions for each image in the batch (however, all 14 cams have the same attributions in this case). 

Is there something I am missing in my code? The intended behavior is in the targets=None, but I would like to be able to do attribution for each image wrt each class.

If you need more information, please let me know too!

**Comment by dimasquest** [comment]
here is a full processing step just in case 
```
def denorm_images(image_batch, grayscale_cam, mean, std):
    # images - entire batch; grayscale_cam - GCams of a single class per each image
    images, visualizations = [], []
    for i, b in enumerate(image_batch):
        # denormalise the images 
        image = np.float32(b * std + mean)
        # make them plt-compatible
        image = image.transpose(1, 2, 0)
        # follow GCam repo and have a visual single image - single class 
        visualization = show_cam_on_image(image, grayscale_cam[i], use_rgb=True)
        # convert into a plt-compatible format
        visualizations.append(torch.from_numpy(visualization.astype(np.float32) / 255.).permute(2, 0, 1))
        images.append(torch.from_numpy(image.astype(np.float32) / 255.).permute(2, 0, 1))
    return images, visualizations


def process_gradcams(image_batch, grayscale_cams, mean, std):
    images, visualizations = [], []
    for graycam in grayscale_cams:
        ims, vis = denorm_images(image_batch, graycam, mean, std)
        images.append(ims)
        visualizations.append(vis) 
    return images, visualizations
```

**Comment by jacobgil** [comment]
Ok I think there is a chance I understand what's going on.

```python
grayscale_cams = [cam(input_tensor=selected_images, targets=[ClassifierOutputTarget(i)]) for i in range(num_classes)]
```

When using targets, it should be a list with a target for every image in the batch.
This is passing only a single target, so it's used for the first image in the batch.

Please change this to something like:

```python
batch_cams_per_category = []
for i in range(num_classes):
    batch_targets=[ClassifierOutputTarget(i) for _ in range(len(input_tensor)]
    category_cams = cam(input_tensor=selected_images, targets=batch_targets)
    batch_cams_per_category.append(category_cams)
```
batch_cams_per_category will be a list of lists, where every element is a list of the batch cams for each of the categories.

Does this work ?

**Comment by dimasquest** [comment]
this works exactly as expected, thank you
