### ISSUE TITLE
Generate Heatmap for each object one by one

### ISSUE THREAD

**Issue by niclastrelle** [jacobgil/pytorch-grad-cam#333]
Hi,

is it somehow possible to generate the heatmap for each instance of one class seperately?

If I have the class cats and an image with 3 cats in it, I would like to gererate 3 seperate heatmaps for each cat. Can this even be achieved?

Thanks in advance

**Comment by jacobgil** [comment]
Let's see.
Can you assume the heatmaps of the 3 cats don't overlap with each other?

If we can assume that, we could just find the global heatmap for the cat category, and then separate it into connected components, and zero out the rest of the components in the heatmap of each of the cats.

Will the heatmaps spatially overlap ?

Can you share an example image  ?
