### ISSUE TITLE
Incompatibility with cuda

### ISSUE THREAD

**Issue by timlai4** [jacobgil/pytorch-grad-cam#346]
I am attempting to use the environment as follows: 

1. I set up Anaconda for Win64.
2. I set up a Python environment via `conda create -n test python -y`
3. I install your environment with pip using `pip install grad-cam`, after activating the environment. 

Afterwards, I try the following:

```
import torch

torch.cuda.is_available()
```
which returns False. However, I am running this on a GPU system. Indeed, when I test this with my own PyTorch environment, the same command returns True. Please let me know if there's something I missed.

**Comment by jacobgil** [comment]
What is the pytorch version you have?

The only requirement that could affect that would be 
torch>=1.7.1
in requirements.txt.

This seems like a general pytorch issue.

try
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
?
(taken from the interactive table here: https://pytorch.org)

**Comment by timlai4** [comment]
Thanks! This worked.
