### ISSUE TITLE
2D ResNet for Video Classification

### ISSUE THREAD

**Issue by koyakuwe** [jacobgil/pytorch-grad-cam#353]
Is it possible to use this tool for drawing grad-cam when my model is based on 2D ResNet and is trained on Kinetics dataset? My input shape is (NT x C x H x W).  Thank you.
@jacobgil

**Comment by jacobgil** [comment]
What is the model input and output ? Does it classify every frame separately? Internally it's just a resnet ?

I would start from just creating a visualization with GradCAM using a batch.
