### ISSUE TITLE
Target for Swin Transformer built from huggingface: axis 3 is out of bounds for array of dimension 3

### ISSUE THREAD

**Issue by chungdz** [jacobgil/pytorch-grad-cam#355]
Hi,

I'm using the Swin-B built from huggingface to do classification tasks. I want to use the GradCAM to do visualization. 

My code is copied from main page:

```
cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True)
grayscale_cam = cam(input_tensor=input_tensor['pixel_values'], targets=None)
```

My input tensor is a batch of RGB images with shape [32, 3, 224, 224]. I select target layer as:

`target_layers = [model.backbone.transformer.encoder.layers[-1].blocks[-1].layernorm_before]`

which is the layernorm used in the same position as what you suggest in the main page. It is in the last layer of the last block. The open source code of Swin Transformer in huggingface can be found [here](https://github.com/huggingface/transformers/blob/v4.24.0/src/transformers/models/swin/modeling_swin.py#L594). Line 594 is the row that declare the layernorm layer I used.

However, I met this error and don't know if there're other layer I could use. Could you kindly help me with this?

thanks,

**Comment by jacobgil** [comment]
Looks like a reshape transform is missing, Please try the section about swin transformers here:
https://jacobgil.github.io/pytorch-gradcam-book/HuggingFace.html

**Comment by chungdz** [comment]
Thank you so much. I successfully visualized transformer models built by my own.
