### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by RMobina** [jacobgil/pytorch-grad-cam#374]
I want to use my own model but get the following error:

`model1 = torch.load('RCTNet.h5')
target_layers = [model1.speaker_encoder.pre_tdnn.layer3]

img_path = "./eagle.jpg"
test_image = Image.open(img_path).convert('RGB')
imgplot = plt.imshow(test_image)
plt.show()

toTensor =  transforms.Compose([
                transforms.Resize((100,100)),
                transforms.ToTensor(),
                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
            ])
input_tensor = toTensor(test_image)

test_image = np.array(test_image)
test_image = cv2.resize(test_image,(100,100))
test_image = test_image.astype('float32')
test_image /= 255.0

imgplot = plt.imshow(test_image)
plt.show()

cam = GradCAM(model=model1, target_layers=target_layers, use_cuda=True)
grayscale_cam = cam(input_tensor=input_tensor, targets=None)

grayscale_cam = grayscale_cam[0, :]
visualization = show_cam_on_image(test_image, grayscale_cam)
imgplot = plt.imshow(visualization)
plt.show()`

**Error:**
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject
Traceback (most recent call last):
  File "/home/ECAPA-TDNN/visualization.py", line 54, in <module>
    grayscale_cam = cam(input_tensor=input_tensor, targets=None)
  File "/home/Voice/venv/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 188, in __call__
    return self.forward(input_tensor,
  File "/home/Voice/venv/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 74, in forward
    outputs = self.activations_and_grads(input_tensor)
  File "/home/Voice/venv/lib/python3.8/site-packages/pytorch_grad_cam/activations_and_gradients.py", line 42, in __call__
    return self.model(x)
  File "/home/Voice/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Voice/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _forward_unimplemented
    raise NotImplementedError
NotImplementedError

**Comment by jacobgil** [comment]
It looks like the model passed can't complete a forward pass.

Can you try running the model on an input tensor, outside of the call to cam?

**Comment by RMobina** [comment]
Many thanks @jacobgil  for your response. I attempted to run the saved model independently on an input tensor, and it was successful.  So it seems the reason not return to input or model. There is some problems in "cam" module. Do you have any idea how can I solve this issue?

**Comment by RMobina** [comment]
Many thanks @jacobgil for your response. I attempted to run the saved model independently on an input tensor, and it was successful. So it seems the reason not return to input or model. There is some problems in "cam" module. Do you have any idea how can I solve this issue?

`ECAPAModel(
  (speaker_encoder): ECAPA_TDNN(
    (torchfbank): Sequential(
      (0): PreEmphasis()
      (1): MelSpectrogram(
        (spectrogram): Spectrogram()
        (mel_scale): MelScale()
      )
    )
    (specaug): FbankAug()
    (pre_tdnn): PreTDNN(
      (block1): Sequential(
        (0): Conv2d(1, 128, kernel_size=(3, 3), stride=(2, 1), padding=(1, 1))
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
      )
      (block2): BasicBlock(
        (layer): Sequential(
          (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (activ): ReLU(inplace=True)
      )
      (block3): BasicBlock(
        (layer): Sequential(
          (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (activ): ReLU(inplace=True)
      )
      (block4): Sequential(
        (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 1), padding=(1, 1))
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
      )
    )
    (conv1): Conv1d(2560, 1024, kernel_size=(5,), stride=(1,), padding=(2,))
    (relu): ReLU()
    (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (layer1): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer2): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer3): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer4): Conv1d(3072, 1536, kernel_size=(1,), stride=(1,))
    (attention): Sequential(
      (0): Conv1d(4608, 256, kernel_size=(1,), stride=(1,))
      (1): ReLU()
      (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): Tanh()
      (4): Conv1d(256, 1536, kernel_size=(1,), stride=(1,))
      (5): Softmax(dim=2)
    )
    (bn5): BatchNorm1d(3072, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (fc6): Linear(in_features=3072, out_features=192, bias=True)
    (bn6): BatchNorm1d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (speaker_loss): AAMsoftmax(
    (ce): CrossEntropyLoss()
  )
)`

**Comment by RMobina** [comment]
Many thanks @jacobgil for your response. I attempted to run the saved model independently on an input tensor, and it was successful. So it seems the reason not return to input or model.  Do you have any idea how can I solve this issue?

**Here is source code:**
audio_file = "00001.wav"
waveform, sample_rate = torchaudio.load(audio_file)
spec = spectrogram(waveform)
data_waveform, rate_of_sample = torchaudio.load(audio_file)
audio_spectogram = torchaudio.transforms.Spectrogram()(data_waveform)

model = torch.load('standard_model.pt')
target_layers = [model.speaker_encoder.pre_tdnn.block4[-1]]
cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True)
grayscale_cam = cam(input_tensor=spec, targets=None)  

grayscale_cam = grayscale_cam[0, :]

**Here is my model:**
ECAPAModel(
  (speaker_encoder): ECAPA_TDNN(
    (torchfbank): Sequential(
      (0): PreEmphasis()
      (1): MelSpectrogram(
        (spectrogram): Spectrogram()
        (mel_scale): MelScale()
      )
    )
    (specaug): FbankAug()
    (pre_tdnn): PreTDNN(
      (block1): Sequential(
        (0): Conv2d(1, 128, kernel_size=(3, 3), stride=(2, 1), padding=(1, 1))
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
      )
      (block2): BasicBlock(
        (layer): Sequential(
          (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (activ): ReLU(inplace=True)
      )
      (block3): BasicBlock(
        (layer): Sequential(
          (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): ReLU(inplace=True)
          (3): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
          (4): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
        (activ): ReLU(inplace=True)
      )
      (block4): Sequential(
        (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 1), padding=(1, 1))
        (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace=True)
      )
    )
    (conv1): Conv1d(2560, 1024, kernel_size=(5,), stride=(1,), padding=(2,))
    (relu): ReLU()
    (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (layer1): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer2): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(3,), dilation=(3,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer3): Bottle2neck(
      (conv1): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn1): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (convs): ModuleList(
        (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (1): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (2): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (3): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (4): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (5): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
        (6): Conv1d(128, 128, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
      )
      (bns): ModuleList(
        (0): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (3): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (5): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (6): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (conv3): Conv1d(1024, 1024, kernel_size=(1,), stride=(1,))
      (bn3): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (se): SEModule(
        (se): Sequential(
          (0): AdaptiveAvgPool1d(output_size=1)
          (1): Conv1d(1024, 128, kernel_size=(1,), stride=(1,))
          (2): ReLU()
          (3): Conv1d(128, 1024, kernel_size=(1,), stride=(1,))
          (4): Sigmoid()
        )
      )
    )
    (layer4): Conv1d(3072, 1536, kernel_size=(1,), stride=(1,))
    (attention): Sequential(
      (0): Conv1d(4608, 256, kernel_size=(1,), stride=(1,))
      (1): ReLU()
      (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): Tanh()
      (4): Conv1d(256, 1536, kernel_size=(1,), stride=(1,))
      (5): Softmax(dim=2)
    )
    (bn5): BatchNorm1d(3072, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (fc6): Linear(in_features=3072, out_features=192, bias=True)
    (bn6): BatchNorm1d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (speaker_loss): AAMsoftmax(
    (ce): CrossEntropyLoss()
  )
)

**Comment by jacobgil** [comment]
Hi,
Trying to understand what this could be.
Did you do model(tensor), or model.forward(tensor), or something else?

The error comes from `return self.model(x)`, so I want to make sure it was applied in the same way, or is there anything else that could be different?
