### ISSUE TITLE
Applying to customized pre-trained model.

### ISSUE THREAD

**Issue by gereziherw** [jacobgil/pytorch-grad-cam#39]
Anything to Modify when we apply to new customized Model, like Resnet50, I got the following error. In the first run, it works, when I run it for the second time, It raises the following error. (My Resnet model is customized for Binary classifier as a feature extractor).
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-153-999f21a4dda6> in <module>()
     16 #model = models.resnet50(pretrained=True)
     17 model = model_ft
---> 18 grad_cam = GradCam(model=model, feature_module=model.layer4, target_layer_names=["2"], use_cuda=use_cuda)
     19 
     20 img = cv2.imread(image_path, 1)

2 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in train(self, mode)
   1070         self.training = mode
   1071         for module in self.children():
-> 1072             module.train(mode)
   1073         return self
   1074 

AttributeError: 'builtin_function_or_method' object has no attribute 'train'

**Comment by gereziherw** [comment]
Issue solved by loading the saved model. i,e. line 17
model = torch.load('model_ft.h5')

**Comment by zhwp** [comment]
I have the same problem too. It seems that reloading the model every time has a high IO with the harddive and the speed would be low.

**Comment by ageryw** [comment]
> I have the same problem too. It seems that reloading the model every time has a high IO with the harddive and the speed would be low.

Zhwp: I saved the learned model as h5 file, and loading the h5 instead of the model name works fine, try that.

**Comment by zhwp** [comment]
> > I have the same problem too. It seems that reloading the model every time has a high IO with the harddive and the speed would be low.
> 
> Zhwp: I saved the learned model as h5 file, and loading the h5 instead of the model name works fine, try that.

OK, Thanks!
