### ISSUE TITLE
NaNs in masks generated by ScoreCAM when using resnet50

### ISSUE THREAD

**Issue by marios1861** [jacobgil/pytorch-grad-cam#404]
I am getting NaNs in masks when using ScoreCAM in resnet50. I have no idea on what could be wrong because the same exact code works fine for vgg16 and vit_b_16. I added a warning on the output of the ScoreCAM method `get_cam_weights` if the weights variable contains NaNs. I then traced back the error to line 40 of [score_cam.py](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/score_cam.py), specifically in some cases $maxs = mins$. After further inspection, it looks like the upsampled activations (and probably the original activations) happen to have totally deactivated channels (all elements are zero in the spatial dimensions). I don't know how to proceed from here. I am using the resnet50 weights from torchvision, as in the example, and my data is from the imagenet evaluation dataset. Also, everything works fine for gradcam and gradcam++

**Comment by YuboHe** [comment]
same here, scorecam returns NaNs for resnet and densenet

**Comment by mxmlnwbr** [comment]
+1

**Comment by marios1861** [comment]
Seems to be fixed for me. Must have been the pytorch 2.0 fallout.

**Comment by mxmlnwbr** [comment]
> Seems to be fixed for me. Must have been the pytorch 2.0 fallout.

What did you do to fix it?

**Comment by marziehoghbaie** [comment]
I'm using torch1.12 but still getting the same issue
