### ISSUE TITLE
 I have fine-tuned VGG19_bn on my custom image set. 

### ISSUE THREAD

**Issue by bemoregt** [jacobgil/pytorch-grad-cam#41]
Hi, @mingloo @jacobgil @jdecid @ChaiKnight @flyingpot 

I have fine-tuned VGG19_bn on my custom image set. 
Please guide how to modify the code to use my model.

Thank you!
Best.
@bemoregt.

**Comment by jacobgil** [comment]
Just set target_layer = 
Please see the updated readme :-)
