### ISSUE TITLE
BinaryClassifierOutputTarget Error

### ISSUE THREAD

**Issue by sarahyutonghan** [jacobgil/pytorch-grad-cam#410]
Hi, thank you for this repository!

I am trying to create some saliency maps on a Bayesian CNN, which is a regression model, but I am getting an error when I try to define the target using `BinaryClassifierOutputTarget`, which is the class I believe you constructed for regression problems. Here is my code and the resulting error:

![image](https://user-images.githubusercontent.com/104859298/230703935-06082048-cc38-4859-9f3e-859fa139c083.png)

The model layer that I am trying to access has the following structure:

![image](https://user-images.githubusercontent.com/104859298/230703974-3c0c811c-e548-4b2e-913a-a9f79a7a4b92.png)

What exactly is going wrong? The code runs fine when I specify `targets = None` but I am not sure why.

**Comment by jacobgil** [comment]
It looks like the spatial output shape is not batch x 1, but there is an extra dimension.
Can you share the exact output shape of the model ?

**Comment by sarahyutonghan** [comment]
Thank you for the fast reply! The output of the model is torch.Size([1, 34]). This is because the model is performing predictions for several "questions" at once.

**Comment by jacobgil** [comment]
In that case the model output is not binary, but a lot of binary outputs.

What you can do is create a custom multi-label target.
I think this should work, output_index should be in the range [0, 33] depending on the output you want to visualize.

```python
class MultiLabelBinaryClassifierOutputTarget:
    def __init__(self, output_index, category):
        self.category = category
        self.output_index = output_index

    def __call__(self, model_output):
        if self.category == 1:
            sign = 1
        else:
            sign = -1
        return model_output[:, output_index] * sign
```

**Comment by sarahyutonghan** [comment]
It worked! Thank you so much!!
