### ISSUE TITLE
Grad cam on 3d Point cloud data 

### ISSUE THREAD

**Issue by abhigoku10** [jacobgil/pytorch-grad-cam#48]
@mingloo @jacobgil  thanks for open sourcing the code , can we perform grad cam on the point cloud data for 3D object detection architecture ? if so can you please share the method or references

**Comment by frgfm** [comment]
I just added support of tensors with more than 2 spatial dimensions to my library for CAM methods if you're still looking for a long-term option: https://github.com/frgfm/torch-cam
I'd be glad to get some feedback :ok_hand:

**Comment by abhigoku10** [comment]
@frgfm  thanks for the code base will test it on point cloud , for point cloud data inference  also we should run the cam similar on images right ?

**Comment by frgfm** [comment]
@abhigoku10 yes, I only provide visualization utils for 2D images, but the CAM itself is being tested by the CI for both 2D and 3D spatial inputs!

**Comment by jacobgil** [comment]
Hi @abhigoku10 
Can you please share more details about the network architecture.
In general you need two things:

1. Define target_loss = 
2. You might need to implement custom logic in get_loss:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/base_cam.py#L32

**Comment by jacobgil** [comment]
Btw @frgfm 
This repo is going to be a log term option as well :-)

**Comment by jumptiger66** [comment]
@abhigoku10 
Hello , Have you solved this problem? If I want to use Pointnet to classify point cloud data, how can I use this repo to get heatmap?
Best regards!
