### ISSUE TITLE
[Q] Are CAMs generated using the output of the specified layer or its input?

### ISSUE THREAD

**Issue by NightMachinery** [jacobgil/pytorch-grad-cam#487]
In the readme, it's specified that the CAM is computed with:

> ViT: model.blocks[-1].norm1

But it's not clear if its the input of `norm1` or the output of `norm1`.

**Comment by jacobgil** [comment]
The output

**Comment by NightMachinery** [comment]
@jacobgil Thanks. Have you done any kind of evaluations for choosing the output of norm1 instead of its input? Or is it just a random guess?
