### ISSUE TITLE
how to visual the specific channels of feature?

### ISSUE THREAD

**Issue by lao-ling-jie** [jacobgil/pytorch-grad-cam#49]
good work! i have question about how to visual the specific of feature?
Like this, visual the first channel to third channel
![image](https://user-images.githubusercontent.com/50287419/97307133-49602500-189a-11eb-8bb7-287bb09382aa.png)

**Comment by NymnW** [comment]
Hi, I'd like to know this as well! Did you ever figure it out?

**Comment by lao-ling-jie** [comment]
> Hi, I'd like to know this as well! Did you ever figure it out?

No, I give up

**Comment by MaxwellHogan** [comment]
@lao-ling-jie can you link source? just trying to better understand what you mean

**Comment by lao-ling-jie** [comment]
> @lao-ling-jie can you link source? just trying to better understand what you mean

Thank you very much. For example, the feature map of last resnet block in Resnet50 is 2048*7*7 (for input image of 224*224).  I want to visualize the first channel of this feature map. How to operate ?

**Comment by MaxwellHogan** [comment]
so by channel are you talking the RGB

**Comment by lao-ling-jie** [comment]
No，it's a specific channel of feature map

**Comment by MaxwellHogan** [comment]
I think I did what you were looking for if I am understanding it correctly - the for loop in line 117 is creating the merged feature map, 

therefore the first channel can be accessed here using the following line:
```
        firstcam = weights[1] * target[1, :, :]

        for i, w in enumerate(weights):
            cam += w * target[i, :, :]
```

I have zipped my code and you can Ctrl+F firstcam to see what I have done elsewhere in the doc
![firstcam](https://user-images.githubusercontent.com/31250274/105827083-71eedc80-5fb9-11eb-8476-4c9727ef8dfc.jpg)


[gradcam_v1.zip](https://github.com/jacobgil/pytorch-grad-cam/files/5872414/gradcam_v1.zip)

**Comment by lao-ling-jie** [comment]
Thank you so much. I will verify it later.

**Comment by MaxwellHogan** [comment]
@lao-ling-jie verified?

**Comment by lao-ling-jie** [comment]
> @lao-ling-jie verified?

I got the corresponding heat map，and think it works.
