### ISSUE TITLE
 Do I need to use my own classifier

### ISSUE THREAD

**Issue by lao-ling-jie** [jacobgil/pytorch-grad-cam#50]
Hi！Thanks for your wonderful work! I have a question about do I need to use my own classifier instead of the original FC layer when I test my own model which treats resnet50 as backbone?

Hope for your answer! @jacobgil

**Comment by 123wk45678** [comment]
i want to kown it too

**Comment by jacobgil** [comment]
Hi,
You just need two things:
1. Load your own model
2. Define target_layer =, one of the layers in the model.
Please see the updated readme.
