### ISSUE TITLE
Grad CAM for multiple input arguments

### ISSUE THREAD

**Issue by IshitaB28** [jacobgil/pytorch-grad-cam#501]
I am trying to use GradCam on my model that takes more than one input arguments. I tried to pass *input_tensor instead of input_tensor since I have a list of 4 arguments. I was trying to modify the source code accordingly. I am facing a series of errors. I am at this point now:
Traceback (most recent call last):
  File "/home/ishita-wicon/Documents/QA/ISIQA/UNET/expl_exp.py", line 449, in <module>
    grayscale_cam = cam(input_tensor=[left_patches, right_patches, left_image_patches, right_image_patches], targets=targets)
  File "/home/ishita-wicon/.local/lib/python3.10/site-packages/pytorch_grad_cam/base_cam.py", line 192, in __call__
    return self.forward(input_tensor,
  File "/home/ishita-wicon/.local/lib/python3.10/site-packages/pytorch_grad_cam/base_cam.py", line 105, in forward
    cam_per_layer = self.compute_cam_per_layer(*input_tensor, #changes to * for list
TypeError: BaseCAM.compute_cam_per_layer() takes 4 positional arguments but 7 were given

Is there any other way?

**Comment by Studentpengyu** [comment]
Hi there, I am facing a similar issue. My model requires an input that consists of a list containing two tensors. How did you handle this? Could you share your solution?

**Comment by IshitaB28** [comment]
Hi, so I handled it by combining the inputs into one tensor and then separating them out in the forward function of my model. 

For example if you need to input 4 things into your model, you do:

**inp = torch.cat((a, b, c, d), dim = 0)
inp = inp.view(4, 64, 1, 32, 32)
grayscale_cam = cam(input_tensor=inp, targets=None)**

And then, in the forward function of your model:

**def forward(self, inp):
        a, b, c, d = inp[0], inp[1], inp[2], inp[3]**
        
 before you proceed with further steps

**Comment by Studentpengyu** [comment]
Thank you for your prompt response. I will try it!

**Comment by Studentpengyu** [comment]
Hi there, I wanted to let you know that my issue has been resolved. 

Here is my solution:
I moved the text features as fixed features into the **forward** function. Since my text features are extracted using a large language model and do not need updating, this approach works well.

Thank you for your help!

**Comment by IshitaB28** [comment]
Hello, good to know that its solved now. Thanks for sharing the issue and the solution!
