### ISSUE TITLE
The newest code is not available for the images without 224*224 shape.

### ISSUE THREAD

**Issue by JunyiA** [jacobgil/pytorch-grad-cam#51]
I tried to process the original images in the ImageNet dataset, which are not 224*224. However, I got: 
"   cam = heatmap + np.float32(img)
ValueError: operands could not be broadcast together with shapes (500,334,3) (334,500,3)".
I solved this problem by using the cv.resize(img,(224,224)) opertation, but I don't know if there is still a hidden problem.

**Comment by jacobgil** [comment]
Thanks for reporting this.
It's fixed now.
