### ISSUE TITLE
Directly Generate Specific Feature Corresponding to Values in ResNet Output Feature Vector

### ISSUE THREAD

**Issue by symhsym** [jacobgil/pytorch-grad-cam#521]
In my current task, after extracting features using ResNet50, I hope to return the heat map in the original image corresponding to a specific feature, such as the 64th feature, in the [1, 2048] feature vector. Can this be achieved using this code?

**Comment by symhsym** [comment]
Because the final prediction model and the feature extraction model are separate, the prediction results reveal the feature vector and feature importance. I hope to create a visualization explaining the regression decisions based on the top-importance feature. Is this feasible? Thank you very much. @

**Comment by jacobgil** [comment]
@symhsym 
Yes indeed.

The ActivationsAndGradients class is used internally to extract activations, but you can also use it yourself.

```python
from pytorch_grad_cam.activations_and_gradients import ActivationsAndGradients
activations_and_grads = ActivationsAndGradients(model, target_layers, reshape_transform)
outputs = activations_and_grads(input_tensor)

# Getting the activations
activations_list = [a.cpu().data.numpy() for a in self.activations_and_grads.activations]
```

**Comment by symhsym** [comment]
Thank you very much for your response. While awaiting your reply earlier, I attempted the following approach. Could you please review it and let me know if it is reasonable?

First, I configured the ResNet model to include only the feature extraction part, removing the fully connected layers.

`model = timm.create_model("resnet50", pretrained=False, in_chans=weights.meta["in_chans"], num_classes=0)
model.load_state_dict(weights.get_state_dict(progress=True), strict=False)
model.eval()`

Next, I directly used the i th value as the ClassifierOutputTarget and then employed GradCAM for visualization.

`input_tensor = x
cam = GradCAM(model=model, target_layers=target_layers)
targets = [ClassifierOutputTarget(i)]
grayscale_cam = cam(input_tensor=input_tensor, targets=targets)
grayscale_cam = grayscale_cam[0, :]
rgb_image = np.transpose(selected_image, (1, 2, 0))
visualization = show_cam_on_image(rgb_image, grayscale_cam, use_rgb=True)`


The results I obtained using this approach appear to be reasonable. However, if you see any potential issues with this method, please let me know. 

Your assistance is extremely valuable to me, especially as this is for my thesis. I intend to acknowledge your help in my paper.

**Comment by jacobgil** [comment]
@symhsym I think there might be a problem here.
What the [ClassifierOutputTarget does ](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/utils/model_targets.py)is simply take the second coordinate (in an expected tensor with two dimensions). 

However your case the i'th activation channel is an image by it self of shape 2048 x rows x cols.
I think model_output[:, self.category] will take the i'th row, and not the i'th channel.

This could be solved easily by defining a custom OutputTarget that takes the i'th channel:
```python
class ActivationChannelTarget:
    def __init__(self, channel):
        self.channel= channel

    def __call__(self, model_output):
        return model_output[channel, :]
```

But i'm not sure what is the purpose of doing so !

You could just take the i'th channel as is and visualize it (by scaling to [0, 1] or [0, 255] first).
It's an image - it lets you see what pixels get activated in the i'th channel and which don't.
It seems to be the perfect attribution map for itself.

**Comment by symhsym** [comment]
Hi, @jacobgil 
Thank you very much for your prompt response to my question. 
I need to clarify that the model I'm using includes a global average pooling layer, so the final output shape is [1, 2048] with two dimensions. Does this approach eliminate any issues?

**Comment by jacobgil** [comment]
You can just remove the GAP as well. The activations will have the shape 2048 x rows x cols. And then take the i'th feature, which will have the shape rows x cols.

**Comment by symhsym** [comment]
I see, Thank you for your help.
