### ISSUE TITLE
Which commit is the stable version, and do you plan to create a tag?

### ISSUE THREAD

**Issue by ytfksw** [jacobgil/pytorch-grad-cam#54]
Which commit is the stable version, and do you plan to create a tag?

**Comment by jacobgil** [comment]
The latest commit should be the stable version.

**Comment by jacobgil** [comment]
Do you think it's worth tagging the master branch as "stable" ?

**Comment by ytfksw** [comment]
@jacobgil 
Thanks for the reply!

I have understood that the master is always working correctly.

I see that there has been a recent improvement. It's great that there are active changes, but I thought it would be hard to use without worry.

If a tag is set up, users will immediately know that there is a stable version and can use it with confidence.

Also, I'd like to contribute to the improvement!
