### ISSUE TITLE
sorting gradients and features for multiple layer 

### ISSUE THREAD

**Issue by MaxwellHogan** [jacobgil/pytorch-grad-cam#57]
this is not a issue so much as a suggestion,

I have been using you code to analyse multiple layers in my network, one of the things I have added is to reverse the list which stores the gradients:
`gradients.reverse()`

This is because the outputs/targets are recorded on the forward pass - therefore the first output corresponds to the first layer I am calculating the activation map for.

whereas, the gradients are recorded in back propagation - therefore the first gradient corresponds to the last layer I am calculating the activation map for. 

therefore in order to make sure I have the correct output and gradient combination the `gradients.reverse()` is required. I have modified the code too much to know exactly where the best place to call this is but I think it should be within get gradients function:

`
def get_gradients(self):
        self.feature_extractor.gradients.reverse()
        return self.feature_extractor.gradients
`

**Comment by cxqzjhz** [comment]
I also see this problems in my project. The order of forward in the computation graph is quite opposite of the order of backward in the graph. The gradient of the last tensor will be  firstly appended in the python list.

**Comment by MaxwellHogan** [comment]
I have started using a python dictionary with the layer is the key so that the correct features are matched to the correct gradients

**Comment by jacobgil** [comment]
Thanks for the feedback.
This was done in the latest PR!
