### ISSUE TITLE
Visualizing Heat Maps for weakly supervised models.

### ISSUE THREAD

**Issue by dhagashshah9** [jacobgil/pytorch-grad-cam#59]
Hi, 

Can anyone throw some light on how to implement GradCAM on weakly-supervised models containing the CNN+LSTM arch (OCR Model)? Majority of the repos show how it can be done on the class-specific models.

**Comment by jacobgil** [comment]
Can you share the model architecture?
But in general you would need to choose a target_layer from the network, that outputs 2D heatmaps.
