### ISSUE TITLE
How to get these data(means = [0.485, 0.456, 0.406]  stds = [0.229, 0.224, 0.225]) in your code?

### ISSUE THREAD

**Issue by estelle1722** [jacobgil/pytorch-grad-cam#6]
In your code same data is as follows:
    **means = [0.485, 0.456, 0.406]  stds = [0.229, 0.224, 0.225]**
These are not standard deviation and mean of single image(both.png in your project).And I wonder how to get these data.
Thank you!

**Comment by sumitbinnani** [comment]
This is from the imagenet data.

**Comment by tsaizehua** [comment]
It is the mean and std of the train dataset, you may calculate it and then normalize the train dataset. https://discuss.pytorch.org/t/normalization-in-the-mnist-example/457/10
