### ISSUE TITLE
cannot import name 'CAM'

### ISSUE THREAD

**Issue by SoroushF79** [jacobgil/pytorch-grad-cam#65]
Running 'from pytorch_grad_cam import CAM' produces 'ImportError: cannot import name 'CAM' '

**Comment by jacobgil** [comment]
Hi,
How did you install the package?

Can you please 
`try pip install -e . `
After cloning the repo.

The pypi repo is not updated yet with the latest version - I asked access from one of the contributers that openned it.
If it won't solve soon I will probably upload it to pypi with another name.

**Comment by AshishAJ1994** [comment]
> Running 'from pytorch_grad_cam import CAM' produces 'ImportError: cannot import name 'CAM' '

Facing the same issue.

**Comment by AshishAJ1994** [comment]
> Hi,
> How did you install the package?
> 
> Can you please try
> `pip install -e . `
> After cloning the repo.
> 
> The pypi repo is not updated yet with the latest version - I asked access from one of the contributers that openned it, and in the meanwhile I can't push updates.
> If it won't solve soon I will probably upload it to pypi with another name.

Is this resolved yet?

**Comment by jacobgil** [comment]
Not yet.
You can install in the meanwhile with
`pip install -e .` 
after cloning the repository. 

In the next week I will probably open a new pypi repo.

**Comment by jdecid** [comment]
It should be fixed now, once pull request #66 is accepted, which updates the readme on how to install the library. Meanwhile, try to install it with `pip install grad-cam` instead of `pip install pytorch-grad-cam` and try to import CAM as you were doing before, with `from pytorch_grad_cam import CAM`. I hope that it works now!

**Comment by SoroushF79** [comment]
Importing CAM after doing **pip install grad-cam** works. Thanks!

**Comment by jacobgil** [comment]
Thanks! Closing, should be resolved now.
