### ISSUE TITLE
How can I implement Grad-CAM in video action Recognition??

### ISSUE THREAD

**Issue by catherinezll95** [jacobgil/pytorch-grad-cam#67]
Thanks for your good work. In Grad-CAM, the input is (B,C,W,H), but in video action recognition, the input is (B,C*T,W,H) and it will be  (B*T,C,W,H) or (B,T ,C,W,H) in model. So, how to get the CAM of each frame in the video?

**Comment by jacobgil** [comment]
Hi, 
Currently there is no support for running on a batch of images - it accepts a single image of size 1, 3, H, W (3 is color channel)

You will have to get the cam for every member of the batch separately.
For example, if the batch size is B, T, 3, C, H, W, 

``` python
# input tensor is x

# i goes over the batch dimension
for i in range(x.size(0)):
	# j goes over the T dimension
	for j in range(x.size(1)):
	cam_grayscale = cam(input_tensor=x[i, j, :, :].unsqueeze(0),
                                    method="gradcam",
                                    target_category=target_category)
```

**Comment by chengengliu** [comment]
If the input of the model is a clip of images with T as number of images in one clip, which other parts of Grad-Cam should be modified? I noticed that in ```base_cam```, ```img``` is resized according to input tensor shape, which means that resizing will not work under this situation.

**Comment by chengengliu** [comment]
@jacobgil HI Jacob,
if the input of the model is a clip of images with T as number of images in one clip, which other parts of Grad-Cam should be modified? I noticed that in ```base_cam```, ```img``` is resized according to input tensor shape, which means that resizing will not work under this situation.

**Comment by avijit9** [comment]
@chengengliu Have you figured this out?

**Comment by chengengliu** [comment]
> > @chengengliu Have you figured this out?
> 
> 
> 
> I have same quetion about grad-cam used for video recognition.

Hi Leo, sorry for the late reply. I’m sorry I cannot remember the details about how to use it since I did the project two years ago; but yes it is doable, I managed to use it frame by frame, so each image is saved with its CAM concatenation. Maybe try to change the input shape or something. The main flow would be the same.

Hope it will help you.
