### ISSUE TITLE
[Bug]Will run out of memory

### ISSUE THREAD

**Issue by shahansa** [jacobgil/pytorch-grad-cam#71]
https://github.com/jacobgil/pytorch-grad-cam/blob/278c9cd92f3436bc0c9cde7cf0d98f9ff12ed415/pytorch_grad_cam/activations_and_gradients.py#L14

Activations and gradients are getting accumulated in cuda device memory. better to do `self.activations.append(output.cpu().data.numpy())`. same for gradients

**Comment by maiskovich** [comment]
That is a good solution, but just to keep in mind, if you are storing activations and gradients during a training loop, you will end filling memory anyways, in that case, and if you want to use each image activation you will need to clean the activations and gradients list in each step, for example:

`self.activations = []`
` self.activations.append(output.cpu().data.numpy())`

OR

`self.activations = output.cpu().data.numpy()`

**Comment by jacobgil** [comment]
Addressed in latest PR.
Thanks!
