### ISSUE TITLE
Bug report!

### ISSUE THREAD

**Issue by MarcusNerva** [jacobgil/pytorch-grad-cam#73]
Greetings, homie!

Like `heatmap = np.float32(heatmap) / 255`, `np.float32(img)` should be devided by 255.0 as well!
https://github.com/jacobgil/pytorch-grad-cam/blob/87c1a7c9951a986fbcde89b9a7f946f6e04bf0f8/pytorch_grad_cam/utils/image.py#L45

**Comment by jacobgil** [comment]
Hello,
The result will be the same,
`np.float32(heatmap) ` converts heatmap to np.float32, the `/255` division then works on np.float32 and returns np.float32.

**Comment by MarcusNerva** [comment]
> Hello,
> The result will be the same,
> `np.float32(heatmap) ` converts heatmap to np.float32, the `/255` division then works on np.float32 and returns np.float32.

I mean `cam = heatmap + np.float32(img)  / 255.0` rather than `cam = heatmap + np.float32(img)`

**Comment by jacobgil** [comment]
Oh, got it!

In the usage example, img is already passed as a np.float img normalized to [0, 1].

I guess the np.float32(img) is confusing, since it's already float.
If we remove that, do you think it solves the issue?

**Comment by MarcusNerva** [comment]
> Oh, got it!
> 
> In the usage example, img is already passed as a np.float img normalized to [0, 1].
> 
> I guess the np.float32(img) is confusing, since it's already float.
> If we remove that, do you think it solves the issue?

Yes. By the way, how can I apply CAM to those networks who employed soft-attention mechanism? Currently, many models have employed this mechanism.

**Comment by jacobgil** [comment]
What network are you referring to?
Vision Transformers for example, or something else?

**Comment by MarcusNerva** [comment]
> What network are you referring to?
> Vision Transformers for example, or something else?

Yes, can you use Vision Transformers as an example?

**Comment by jacobgil** [comment]
Since vision transformers don't have spatial activation channels, it's more tricky to apply Grad-CAM.
(Will need to think about how exactly to do it).

However, there are other techniques, like attention rollout.

Take a look at this implementation: https://github.com/jacobgil/vit-explain
And a blog post about it: https://jacobgil.github.io/deeplearning/vision-transformer-explainability

**Comment by jacobgil** [comment]
I'm going to soon post examples of using grad-cam with VIT.

**Comment by jacobgil** [comment]
Done!
Check the latest master branch Readme, and also vit_example.py
