### ISSUE TITLE
Doubt regarding ViT from timm 

### ISSUE THREAD

**Issue by sayakpaul** [jacobgil/pytorch-grad-cam#76]
Hi @jacobgil. This is such an amazing piece of work. Thanks to you and all the contributors behind it. 

I am currently, using `vit_base_patch16_224` from `timm` and I am trying to visualize the Grad-CAM maps. I have followed the guidelines you have laid out in the README for ViTs but I am still getting a weird error:

`RuntimeError: shape '[1, 16, 16, 768]' is invalid for input of size 150528`. 

Here's minimal code:

```python
def reshape_transform(tensor, height=14, width=14):
    result = tensor[:, 1 :  , :].reshape(tensor.size(0),
        height, width, tensor.size(2))

    # Bring the channels to the first dimension,
    # like in CNNs.
    result = result.transpose(2, 3).transpose(1, 2)
    return result

vit_model = timm.create_model("vit_base_patch16_224", pretrained=True)

rgb_img = cv2.imread("grace_hopper.jpg", 1)[:, :, ::-1]
rgb_img = cv2.resize(rgb_img, (224, 224))
rgb_img = np.float32(rgb_img) / 255
input_tensor = preprocess_image(rgb_img, mean=[0.485, 0.456, 0.406], 
                                            std=[0.229, 0.224, 0.225])

cam = GradCAM(model=vit_model, target_layer=vit_model.blocks[-1].norm1, 
              use_cuda=True, reshape_transform=reshape_transform)
grayscale_cam = cam(input_tensor=input_tensor, target_category=652)
visualization = show_cam_on_image(rgb_img, grayscale_cam)
```

Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/56e450ea93cd0362656b3fe3ea77fd20/scratchpad.ipynb) for reproducing the issue.

**Comment by jacobgil** [comment]
Hi!
I'm going to look into this and get back to you very soon.

**Comment by jacobgil** [comment]
Hi,
I actually tried running this locally with some image and it worked.
I couldn't run the colab since grace_hopper.jpg was missing, but when I created a random image there of size 224,224,3 it also worked.

Can you provide that image, and maybe re-run and make sure it doesn't work?

**Comment by sayakpaul** [comment]
I just reran and it also worked. Not sure where I made the mistake. However, the visualization seems to be spurious:

![image](https://user-images.githubusercontent.com/22957388/116104527-24742f80-a6ce-11eb-9fa9-a093b8be3665.png)

Here's the full [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/b0452c7224ccae3e5b2583fd6ab9e977/scratchpad.ipynb) (working). Am I passing the wrong `target_layer`? Here's how `vit_model.blocks[-1]` looks like:

```
Block(
  (norm1): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (attn): Attention(
    (qkv): Linear(in_features=768, out_features=2304, bias=True)
    (attn_drop): Dropout(p=0.0, inplace=False)
    (proj): Linear(in_features=768, out_features=768, bias=True)
    (proj_drop): Dropout(p=0.0, inplace=False)
  )
  (drop_path): Identity()
  (norm2): LayerNorm((768,), eps=1e-06, elementwise_affine=True)
  (mlp): Mlp(
    (fc1): Linear(in_features=768, out_features=3072, bias=True)
    (act): GELU()
    (fc2): Linear(in_features=3072, out_features=768, bias=True)
    (drop): Dropout(p=0.0, inplace=False)
  )
)
```

**Comment by jacobgil** [comment]
Can you please try
vit_model.blocks[-1].norm1?

**Comment by jacobgil** [comment]
The reason is that anything after the last attention, will have a gradient of 0 with respect to the class token.
I tried communicating that in the readme.

I will also try now on this image :-)

**Comment by sayakpaul** [comment]
> Can you please try
vit_model.blocks[-1].norm1?

If you see the Colab Notebook you will see I have done that only. I provided the full output for better visibility. 

> The reason is that anything after the last attention, will have a gradient of 0 with respect to the class token.
I tried communicating that in the readme.

Oh yes, I noticed that when I was reading the documentation. Thanks for being extra careful with that. The explanation is just spot on there.

**Comment by jacobgil** [comment]
![gradcam_cam](https://user-images.githubusercontent.com/5342073/116105771-4ebbf200-a6ba-11eb-93bb-37f117ad558c.jpg)

**Comment by jacobgil** [comment]
Just ran it now on the examples\both.png image.

Re the grace hopper image - I think there is no person category in imagenet, so it might be tricky to interpret it.

**Comment by sayakpaul** [comment]
Also, FWIW, `652` (military uniform) is the class category of the image I am trying.

**Comment by jacobgil** [comment]
Cool.
This is how it looks for gradcam:
![gradcam_cam](https://user-images.githubusercontent.com/5342073/116107018-4e702680-a6bb-11eb-8056-48b316821d54.jpg)

It's a bit weird, so looking into it.

**Comment by sayakpaul** [comment]
I fixed the normalization stats. For ViT (Google), it should be [0.5, 0.5, 0.5] for both mean and std. With this, I got something similar:

![image](https://user-images.githubusercontent.com/22957388/116107217-761db980-a6d0-11eb-8d0c-bace4c8a4011.png)

With a ResNet50, I got:

![image](https://user-images.githubusercontent.com/22957388/116107882-08be5880-a6d1-11eb-8e47-b0bb7fc178c4.png)

For tabby cat (with ViT), I got something expected (on a different image):

![image](https://user-images.githubusercontent.com/22957388/116107381-9d748680-a6d0-11eb-9671-14691b52d183.png)

**Comment by jacobgil** [comment]
For the uniform image, 
target_layer = model.blocks[-2]
seems to work slightly better:
![gradcam_cam](https://user-images.githubusercontent.com/5342073/116108264-6dbb8380-a6bc-11eb-9bb0-1a3afc37d579.jpg)

**Comment by jacobgil** [comment]
(Maybe it memorized the stars in the flag)

But looks like it learned very different patterns than resnet.

**Comment by sayakpaul** [comment]
Yes exactly. Very interesting to see.
