### ISSUE TITLE
Does it work on 3D image as well?

### ISSUE THREAD

**Issue by 9B8DY6** [jacobgil/pytorch-grad-cam#83]
I do age prediction with nifti file(MRI) then I want to use grad cam. Does it work on 3D image, nii(nifti file) as well?

**Comment by jacobgil** [comment]
Hello, it may require some modifications depending on the input and output shapes,
but this should be possible.

Can you please clarify what is the input and output from the network?

Some points to make it work with 3D
- https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/grad_cam.py#L16
Need to change the axis to 2,3,4
Or even better, make it general, and be something like 
axis=[i for i in range(2, len(grads.shape))]

- https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/grad_cam.py#L16
weights might need another None there

- The whole 2d image visualization part assumes 2D and will need to be changed.
https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/base_cam.py#L82

Once you get the 3D saliency map, you will need a nice way to visualize it.
