### ISSUE TITLE
Error: model error while processing through loop

### ISSUE THREAD

**Issue by NeelBhowmik** [jacobgil/pytorch-grad-cam#87]
Hi,
This is a very useful code repo and thanks for sharing. 
I have installed this code using pip (_pip install grad-cam_). Whilst using _cam.py_ on a single image, it works fine. 
However, I have slightly modified the same code to apply on an image directory (in a loop):

1. Initialise the _model_ (resnet18), _cam_, _gb_model_ at the beginning, outside the for loop.
2. Calling the _cam_, _gb_model_ in for loop to apply on each image.
3. You can find the code in the attachment. 
[cam_modified.txt](https://github.com/jacobgil/pytorch-grad-cam/files/6466831/cam_modified.txt)

I am getting the following error:

> File "cam_m.py", line 109, in <module>
    cam_image = activecam(args, cam, gb_model)
  File "cam_m.py", line 86, in activecam
    grayscale_cam = cam(input_tensor=input_tensor,
  File "/home/neel/data/cnn_model/pytorch-grad-cam/pytorch_grad_cam/base_cam.py", line 128, in __call__
    return self.forward(input_tensor,
  File "/home/neel/data/cnn_model/pytorch-grad-cam/pytorch_grad_cam/base_cam.py", line 69, in forward
    self.model.zero_grad()
  File "/home/neel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1331, in zero_grad
    for p in self.parameters():
  File "/home/neel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1089, in parameters
    for name, param in self.named_parameters(recurse=recurse):
  File "/home/neel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1115, in named_parameters
    for elem in gen:
  File "/home/neel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1059, in _named_members
    for module_prefix, module in modules:
  File "/home/neel/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1257, in named_modules
    for m in module.named_modules(memo, submodule_prefix):
AttributeError: 'builtin_function_or_method' object has no attribute 'named_modules'

Could you please help me to solve this error?

Many thanks,
Neel

**Comment by jacobgil** [comment]
Hi,
I will look into this and get back to you in the next few days.
Does this happen already at the first image in the loop?

**Comment by NeelBhowmik** [comment]
Hi,
Two interesting things I have observed:
1. The code I posted above (cam_modified - where I created a cam model initialisation function and then passed to main) - the above error occurs at the first image.
2. When I just inserted a for loop in your original code (cam.py), the same error occurs after the first image processed successfully.

Thanks,

**Comment by jacobgil** [comment]
Thanks for reporting the problem.
It should be fixed now.

The problem was  that the GuidedBackprop part, was replacing ReLU layers with GuidedReLU, but did not restore the model to the original state.

**Comment by jacobgil** [comment]
By the way, if the images are the same size, you can group them into batches for faster computation.

**Comment by jacobgil** [comment]
I'm closing this issue since it seems solved.

**Comment by NeelBhowmik** [comment]
Hi,
Thanks for your quick solution/help. I am able to process the images in a loop.

Thanks
