### ISSUE TITLE
SwinT is not working.

### ISSUE THREAD

**Issue by hcw-00** [jacobgil/pytorch-grad-cam#99]
I tried swinT_example in usage_examples directory. but output cam image is not same as the image in README.
vit_example.py is working properly.

**Comment by yanghongji2007** [comment]
Hi,  have you solved this issue? I found it might work by setting the target layer
```target_layer = model.layers[-1].blocks[-1]```
but I am not quite sure about it

**Comment by jacobgil** [comment]
Hi, 
It appears very sensitive to the target layer and needs to be tuned per model.
Using one of the gradient free methods (--method scorecam, or --methdod ablation cam) seems to work much better with Swin Transformers.
